- pyzo/codeeditor/extensions/appearance.py
- pyzo/codeeditor/highlighter.py
- pyzo/codeeditor/parsers/python_parser.py
- pyzo/codeeditor/parsers/tokens.py
- pyzo/core/editor.py
This (in relation with #366)
- gives a correct algorithm for brace-matching,
- marks unmatched/unbalanced braces with a reddish background and
- adds parenthesis tokens in the python parser to make it possible to correctly ignore strings and comments
- stores each block's token list in its userData object.
> Correcting brace matching

- pyzo/resources/pyzo.desktop
This is the freedesktop file I am currently using for the Debian packaging, as reported in #392.
> Add freedesktop file for Pyzo.

- pyzo/resources/translations/pyzo_zh_CN.tr
Simplified Chinese translation for #402
> Simplified Chinese translation for #402

- pyzo/codeeditor/extensions/appearance.py
- pyzo/core/editorTabs.py
- pyzo/core/menu.py
- pyzo/tools/pyzoFileBrowser/__init__.py
- pyzo/tools/pyzoHistoryViewer.py
- pyzo/tools/pyzoInteractiveHelp.py
- pyzo/tools/pyzoLogger.py
- pyzo/tools/pyzoSourceStructure.py
- pyzo/tools/pyzoWebBrowser.py
- pyzo/tools/pyzoWorkspace.py
- pyzo/util/bootstrapconda.py
> Add translations

- pyzo/codeeditor/extensions/autocompletion.py
- pyzo/core/assistant.py
- pyzo/tools/pyzoHistoryViewer.py
> Fix import errors for some Qt5 components.

- pyzo/core/menu.py
> fixing issue with cursor not advancing when it should

- pyzo/core/menu.py
- pyzo/tools/pyzoHistoryViewer.py
Improve shell history usability
> Shell history aids

- pyzo/codeeditor/extensions/behaviour.py
Moves all lines in selection and keeps these lines selected so they can be moved further.
Originally created from #479
> Update to allow moving multiple lines

- pyzo/core/menu.py
Add a menu entry to change directly to current editor files path.
This is more immediate and very often is useful
> Added a shell menu entry to change directory

- pyzo/tools/pyzoSourceStructure.py
> use color and parenthesis etc. to indicate class def and so on

- pyzo/core/editorTabs.py
sometimes, I need to replace a pattern in all files, it's a bit long to use just replace all if there are many files
> add replaceInAllFiles button

- pyzo/util/_locale.py
solves https://github.com/pyzo/pyzo/issues/567
> use system language for default menu if possible

- pyzo/core/menu.py
Open via Advanced settings from the Settings menu.
The code is based on Workspace plugins and QTreeWidget.
Missing: backup and restore old conf  : (
Best
> Advanced settings editor

- pyzo/core/menu.py
The first warning dialog deleted and wording
> Advanced settings editor cleanup

- pyzo/util/interpreters/__init__.py
solves https://github.com/pyzo/pyzo/issues/575
> workaround badly or unregistered python

- pyzo/resources/translations/pyzo_de_DE.tr
Update and complete German translation
> Update and complete German translation

- pyzo/__init__.py
- pyzo/resources/defaultConfig.ssdf
> Ugly (?) setting to allow for manual fixing of qt scale factor.

- pyzo/pyzokernel/introspection.py
- pyzo/tools/pyzoWorkspace.py
> Fixing enumeration of dict content for workspace

- pyzo/core/kernelbroker.py
- pyzo/core/statusbar.py
Also fixes error in status bar.
> Fix warmup issue

- README.md
- TRANSLATIONS.md
- azure-pipelines.yml
- freeze/freezeScript.py
- freeze/installerBuilderScript.iss
- pyzo/__init__.py
- setup.cfg
- setup.py
Builld binaries (tar.gz, zip, exe installer, dmg) on Azure pipelines using PyInstaller and platform dependent packaging. 🚀
> Build binaries in CI

- pyzo/core/kernelbroker.py
> remove root app dir from LD_LIBRARY_PATH in frozen dirs

- pyzo/pyzokernel/introspection.py
Closes #650. Support for ndarrays is still much nicer in Spyder, but that's for another day.
> improve display in workspace of list, tuple, dict and array

- azure-pipelines.yml
- pyzo/__init__.py
> Try fixing Linux binaries ... again

- pyzo/codeeditor/extensions/autocompletion.py
- pyzo/core/baseTextCtrl.py
fixes #689 
I am not sure I did it in an entirely good way but this seems to work.
> detecting if we're completing after a dot

- pyzo/core/baseTextCtrl.py
- pyzo/resources/defaultConfig.ssdf
> Autocomplete popup with style

- pyzo/core/kernelbroker.py
- pyzo/core/main.py
- pyzo/tools/pyzoFileBrowser/__init__.py
- pyzo/tools/pyzoFileBrowser/browser.py
- pyzo/tools/pyzoFileBrowser/proxies.py
> Close faster

- pyzo/core/main.py
When using Pyzo with PySide2 when closing the IDE we get a Segmentation fault
This patch is a work around for the issue
> Correct Pyzo with PySide2 segmentation fault

- pyzo/codeeditor/manager.py
> much faster font enumeration

- pyzo/core/themeEdit.py
> Pervent errors when syntax style sheets dont have all style elements

- azure-pipelines.yml
- pyzo/codeeditor/extensions/appearance.py
- pyzo/codeeditor/extensions/autocompletion.py
- pyzo/core/compactTabWidget.py
- pyzo/core/themeEdit.py
- pyzo/pyzokernel/guiintegration.py
- pyzo/tools/pyzoFileBrowser/browser.py
Just a whole lot of `int()` casts...
> Stricter typing to fix Pyzo for Pyqt5 with Py3.10

- azure-pipelines.yml
> make ci use released pyinstaller again

- azure-pipelines.yml
- pyzo/__init__.py
- pyzo/pyzokernel/guiintegration.py
> Fix a bug in Qt exec

- pyzo/yoton/connection_tcp.py
Closes #783; its very likely that this issue is circumvented in most cases (it is for me).
> increase stepsize in trying ports

- pyzo/core/menu.py
> Fix keybindings dialog

- freeze/boot.py
- freeze/pyzo_test_frozen.py
> fix macos frozen source dir

- pyzo/pyzokernel/guiintegration.py
Looks like they plan on removing `get_event_loop` eventually.
> future compat

- pyzo/core/pdfExport.py
> fix printing

- pyzo/pyzokernel/_nope.py
- pyzo/pyzokernel/interpreter.py
> Update to latest appnap logic

- pyzo/codeeditor/_test.py
- pyzo/pyzokernel/guisupport.py
> Fix old shebangs

- pyzo/core/themeEdit.py
> Fix that applying a theme is broken on some systems

- .gitignore
- freeze/pyzo_package.py
- pyzo/core/codeparser.py
- pyzo/core/icons.py
- pyzo/tools/pyzoSourceStructure.py
- pyzo/yoton/channels/channels_reqrep.py
- pyzo/yoton/connection_tcp.py
- pyzo/yoton/core.py
- pyzo/yoton/misc.py
- pyzo/yoton/tests/test_speed.py
Closes #812, closes #213, fixes part of #594.
I also ran `black`, so some style fixes.
> Source structure uses theme colors

- doc/yoton/context.rst
- doc/yoton/internals.rst
- pyzo/util/interpreters/__init__.py
- pyzo/yoton/context.py
Closes #812. I did think it worthwhile to go over all cases of "allows to" though.
> Fix some typos

- pyzo/pyzokernel/interpreter.py
python environment running in the shell:
os: Linux
exe: Python 3.11.1 
gui: PySide6 6.5.0
When creating or restarting the shell, it crashes:
```
Fatal Python error: Segmentation fault
Python 3.11.1 (main, Jan 16 2023, 22:41:20) on linux (64 bits).
...
Extension modules: xxsubtype, shiboken6.Shiboken (total: 2)
Segmentation fault (core dumped)
The kernel process exited. (139)
```
Importing `PySide6` will also import module `shiboken6`.
And `shiboken6` replaces python's `__import__` with a custom C function `__feature_import__`.
For every module that is imported as a text file (*.py), shiboken calls its own function `_mod_uses_pyside` and in that function `source = inspect.getsource(module)` is executed.
And python's `inspect.getsource` will call python's `getlines`.
But `getlines` is …
> fix crash of kernel when importing PySide6

- .github/workflows/cd.yml
- .github/workflows/ci.yml
> added missing linux packet for PySide 6.5

- .github/workflows/ci.yml
- pyzo/core/shellInfoDialog.py
- pyzo/pyzokernel/guiintegration.py
- pyzo/qt/QtCore.py
- pyzo/qt/QtGui.py
- pyzo/qt/QtWidgets.py
- pyzo/qt/enums_compat.py
added some fixes to support PyQt6
this will also solve issue #779
> fix support for PyQt6

- pyzo/tools/pyzoFileBrowser/browser.py
The completer did not work because the root path was not set properly.
I did not add code to synchronize the completer with the name filter textbox in order to not add unnecessary complexity.
BTW: still working on another PR
> fix completer in path input textbox in File Browser tool

- pyzo/tools/__init__.py
Python 3.12 has no more `imp` module. Therefore I replaced it with `importlib.util`.
> upgrade from deprecated imp module to importlib

- pyzo/core/shellStack.py
When changing stack frames while debugging and the filepath of the current frame has a special meaning, such as `<string>`, then a message box with the title "Error loading file" is shown two times consecutively and both messages have to be confirmed by the user.
**Fix**
I will treat `<string>` etc. the same as `<console>` and consequently not show any error. To not confuse the user, the focus will be removed from the editor and set to the current shell.
**Reproducing the problem**
* create a normal python file, e.g. "/tmp/abc.py" and put a single line in it: `a = 1`
* open the file in the Pyzo editor and set a breakpoint at that single line
* create a new file in Pyzo and insert the following lines:
```
tt = """
fp = '/tmp/abc.py'
with open(fp, 'rt', …
```
> fix debug focus for special filepath values

- pyzo/codeeditor/extensions/behaviour.py
This PR will make the editor's auto-indent also work for comments after the ":", e.g.:
```
if x > 4:  # check size [PRESS RETURN TO GET TO NEXT LINE]
y = ...  # this line is automatically indented correctly
```
This will solve #804.
> improve python auto-indent

- pyzo/pyzokernel/magic.py
> Fix notebook command for notebook 7.0+

- pyzo/resources/org.pyzo.Pyzo.desktop
This fixes a comment in the desktop file.
> fix comment in desktop file

- pyzo/core/menu.py
Currently, when executing cells, the starts of cells are not parsed properly. Lines starting with `##` in a multiline string literal are misinterpreted as cell comments.
To fix this, I will use the parsed tokens from the editor's syntax highlighter instead. If no Python parser was selected (menu: File -> Syntax parser), the old implementation will be used as a fallback.
> used properly parsed cell comments for runCell

- pyzo/tools/pyzoWorkspace.py
This will allow to delete the selected object in the Workspace tool by pressing the DEL key.
> add DEL shortcut to Workspace tool

- pyzo/pyzokernel/debug.py
Currently, post-mortem debugging does not allow to switch stack frames out of a generator expression.
Example:
```python3
def a_function():
x = 1
another_func()
def another_func():
y = 2
while True:
list(b / 0 for b in range(10))
a_function()
```
Running the example script gives the following output:
```
>>> (executing file "test1.py")
Traceback (most recent call last):
File "/tmp/test1.py", line 13, in <module>
a_function()
File "/tmp/test1.py", line 5, in a_function
another_func()
File "/tmp/test1.py", line 10, in another_func
list(b / 0 for b in range(10))
File "/tmp/test1.py", line 10, in <genexpr>
list(b / 0 for b in range(10))
ZeroDivisionError: division by zero
>>> DB START
(<genexpr>)>>> db where
-> 1: File "/tmp/test1.py", line 10, in <genexpr>
(<genexpr>)>>> 
```
With the fix in …
> improve post-mortem debugging in generator expressions

- pyzo/pyzokernel/debug.py
This is similar to #998.
I have encountered other cases than just generator expressions where only the top frame of the stack in a post-mortem traceback is visible in the debugger:
```python3
import json
with open('/tmp/abc.json', 'wt') as fd:
json.dump({(1,): 2}, fd)  # (tuple is not allowed as json key)
def func1():
yield 1 / 0
list(func1())
```
With this PR, I allow to go back to previous stack frames for post-mortem debugging, even if the current frame has no pointer to the previous frame, and without any restriction to a special code object name.
> improve post-mortem debugging for unlinked frames

- pyzo/core/shell.py
Running code with lots of calls to print functions in a Pyzo shell is quite slow.
```python3
import time
t_start = time.perf_counter()
for _ in range(10000):
print('abc')
print('elapsed:', time.perf_counter() - t_start, 's')
```
One of the reasons is the long shell update interval. This interval was increased in #789 to reduce energy consumption.
In order to have both, fast shell updates and reduced energy consumption, I have added a simple dynamic switching mechanism. When there are shell updates to process, the update interval gets reduced to 10 ms, otherwise it is increased to 100 ms.
During tests I have observed reduced execution times for the given code snippet by a factor of around 2 to 4.
> add dynamic shell update intervals

- pyzo/pyzokernel/introspection.py
The extraction of the signature, which is used for the calltip, does not work for some common objects:
```
bytes(iterable_of_ints) -> bytes
int([x]) -> integer
iter(iterable) -> iterator
min(iterable, *[, default=obj, key=func]) -> value
!!! could not extract the signature of np.linspace !!!
!!! could not extract the signature of np.sum !!!
!!! could not extract the signature of np.array !!!
!!! could not extract the signature of np.linalg.norm !!!
!!! could not extract the signature of pd.DataFrame !!!
!!! could not extract the signature of requests.Request !!!
```
This commit will add another way to obtain the signature. When all current methods fail, `inspect.signature` will be called. And I now allow up to three lines in the doc string to handle cases like
```
>>> …
```
> improve signature extraction for calltips

- pyzo/_start.py
Recently, CI workflows often needed several attempts to have all tests pass.
As fas as I could find out, this was caused by a callback of a QTimer in the test run which was triggered too early.
See the comments in the code for more details.
> add workaround for timer problem in test run

- pyzo/core/main.py
I stumbled upon code that should show a context menu in the main window when right-clicking on the menu bar or the title bar of a panel. But this context menu never worked (at least for Qt5/6). I fixed it, and now tools can be shown/hidden, like in the normal "Tools" menu.
> fix pop-up menu in main window

- pyzo/core/main.py
> fix pop-up menu in main window 2

- pyzo/core/editor.py
- pyzo/core/menu.py
- pyzo/core/pdfExport.py
- pyzo/qt/__init__.py
- pyzo/tools/pyzoFileBrowser/browser.py
I packed three commits into this PR:
- little clean-up of the code
- append ".pdf" to the selected filename in the pdf exporter if not already there
- fix a bug from the Qt6 transition
> fix bug from Qt6 transition and clean-up code

- pyzo/codeeditor/extensions/autocompletion.py
- pyzo/core/commandline.py
- pyzo/core/editorTabs.py
- pyzo/core/shell.py
- pyzo/pyzokernel/interpreter.py
- pyzo/pyzokernel/start.py
- pyzo/tools/pyzoSourceStructure.py
- pyzo/yoton/channels/channels_base.py
- pyzo/yoton/channels/channels_pubsub.py
- pyzo/yoton/channels/channels_reqrep.py
- pyzo/yoton/connection.py
- pyzo/yoton/connection_tcp.py
- pyzo/yoton/context.py
- pyzo/yoton/core.py
Commits:
- fix source structure keeping outdated status bar message
(switching to another editor tab with no code did not update the message)
- fix typos
- only print "file already open" for unexpected filepaths
(this was always spamming the logger tool during debugging)
> apply smaller fixes

- pyzo/pyzokernel/introspection.py
In some cases, calltips were not shown for functions and methods. This was when
a) `inspect.signature` was not able to get the signature
and b) when the function/method has a differnt name than in the first line of the doc string
e.g.:
```python3
import sys
myfunc = sys.getsizeof
myfunc.__doc__  # --> has a docstring starting with "getsizeof("
```
This PR solves the problem by also allowing any valid identifier before the open parenthesis in the docstring.
> improve signature inspection for aliased methods

- pyzo/tools/pyzoFileBrowser/browser.py
- pyzo/tools/pyzoFileBrowser/importwizard.py
- pyzo/tools/pyzoFileBrowser/proxies.py
- pyzo/tools/pyzoFileBrowser/tree.py
see the names and descriptions of the commits
> fix File Browser tool (prevent silent file overwriting and various improvements)

- pyzo/core/editor.py
Closes #1046.
@raymanP could you try out whether this also fixes it for you?
> Fix that app does not receive keyboard after reloading when files changed externally

- pyzo/tools/pyzoSourceStructure.py
This will fix a bug that I introduced via #1023:
```python3
def myfunc():
pass
def otherfunc():
pass
x = 3  # bug: source structure displays "otherfunc" instead of "myfunc" for this line
```
And I also reverted the search algorithm to a linear one in order to keep the code simple.
> fix source structure tool for nested elements

- pyzo/tools/pyzoWorkspace.py
This PR will add new features for the workspace tool, mainly filtering entries by variable name patterns and a button to manually refresh the variables.
The button for manually refreshing the variables is useful when variables are modified by a code that is run in the event loop, for example a `QTimer` callback of a self-made GUI.
There is a new textbox for search expressions at the bottom. The user can enter one or multiple space-separated search patterns to filter the variable names.
The patterns can either be wildcard texts or regular expressions, depending on the settings (button on the right of the new textbox). In the new settings there is also a switch for case sensitivity.
possible wildcards are:
a single question mark (`?`) matches exactly one character
an asterisk (`*`) matches …
> add search text filters and refresh button to the workspace tool

- pyzo/codeeditor/extensions/autocompletion.py
With this PR, the cursor will automatically be moved to the right of the closing bracket after accepting a key autocompletion suggestion.
> move cursor past the closing bracket on key autocompletion

- pyzo/qt/QtGui.py
This will make dropping text in the shell work for PyQt5 as well.
> fix drop event for PyQt5

- pyzo/core/editor.py
There are multiple operations in the editor that expand the selected text to whole selected lines (or the cursor position to the whole line if there was no selection):
- Indent
- Dedent
- Comment
- Uncomment
- Toggle comment
- Duplicate line
- Delete line
- Execute selection
But "Duplicate line" and "Delete line" are a bit different. When having the end of a multi-line selection at the beginning of a line, then these two operations also fully include that last line, unlike all other operations.
With this PR, "Duplicate line" and "Delete line" will have the same line selection behavior as the other operations.
I will wait a few days for feedback before merging this.
> fix line duplication and deletion behavior

- pyzo/pyzokernel/interpreter.py
> Fix traceback

- pyzo/pyzokernel/debug.py
If there is an `ExceptionGroup` in the traceback, post-mortem debugging will only go to the code line where the `ExceptionGroup` was raised. With this PR, individual sub-exceptions (and also nested sub-sub-...-exceptions) can be individually selected for post-mortem-debugging.
The magic command for post-mortem is still `db start`, and this is still the default action when pressing Ctrl+P or selecting "Postmortem" in the "Shell" menu.
This PR changes the following things:
When starting a post-mortem, Pyzo will now detect ExceptionGroups. With no extra argument to `db start`, the first sub-exception that is not an ExceptionGroup will be selected for post-mortem debugging.
And the normal `db start` will inform the user that there are ExceptionGroups and how they can be selected, e.g.:
``` …
```
> add post-mortem debugging for individual sub-exceptions in ExceptionGroups

- pyzo/core/shellStack.py
This PR makes switching the current shell and the current stack frame faster:
When placing the mouse cursor over the QToolButton of the shell toolbar and moving the mouse scroll wheel, the shell resp. the stack frame is switched like when moving the mouse wheel over a QComboBox widget.
> add shell switching and debug frame switching via mouse wheel

- pyzo/core/shell.py
This commit solves two problems regarding text insertion into the shell via the middle mouse button.
In Linux, a press of the middle mouse button typically inserts the currently selected text at the clicked location. This is independent of the contests of the clipboard.
**Current situation before this PR**
In Pyzo (on Linux) this text insertion via middle mouse button click works normally in all the widgets, such as the code editor and various `QLineEdit` elements.
But in the shell widgets, there are two problems:
1) If the current text cursor is in the edit line (after the prompt), the whole `QPlainTextEdit` widget is not in read-only mode. A middle mouse click before the prompt then inserts the text at the clicked position. In the `mousePressEvent`, the middle-button-event is ignored, …
> fix text insertion with middle mouse button in shell on Linux

- pyzo/resources/code_examples/myRunner.py
- pyzo/resources/code_examples/start_external_shell.py
The various code example scripts are now in pyzo/resources/code_examples.
> clean up code examples

- RELEASE_NOTES.md
- pyzo/__init__.py
@bdieterm ready for a release?
> Bump version

- pyzo/core/baseTextCtrl.py
- pyzo/core/editorTabs.py
#1135 is awesome but it did not work on MacOS. This fixes that.
> Fix new tab selector for MacOS

- pyzo/pyzokernel/guiintegration.py
In MS Windows, the following windows or dialogs will most times not directly be visible to the user when the command is executed the first time in a shell/script, because they might be covered by the Pyzo IDE's window:
```python3
dirpath = QtWidgets.QFileDialog.getExistingDirectory()
QtWidgets.QMessageBox().exec()
gui = QtWidgets.QMainWindow(); gui.show()
import matplotlib.pyplot as plt
plt.ion()
plt.figure()
```
But after the user gave the focus to such a window by manually switching to it, all subsequent windows will appear normally in the foreground as expected.
This PR adds a workaround that makes Qt windows appear in the foreground right from the beginning of the shell start without user interaction.
I will keep this PR a draft for a few days for further testing before merging it.
> prevent windows/dialogs from spawning in the background in MS Windows

- pyzo/core/shellInfoDialog.py
This is a rework of the shell configuration dialog to improve usability.
The tab container is replaced with a stacked widget and a list. The list selection switches the visible config form (instead of the tab bar). This is more comfortable when having many shell configurations.
Reordering via drag'n'drop is possible (as before with dragging tabs). Duplicating of configurations via drag'n'drop while pressing the Ctrl key is now possible (which was not possible before).
The dialog window has now a larger default size so that everything can be seen without scrolling or resizing.
In the old version, some buttons had weird positions.
"Add config" was on the top right corner in the tab bar widget.
"Delete" and "Copy" were at the bottom of the QForm and not visible without scrolling or resizing …
> rework shell configuration dialog

- pyzo/core/shellStack.py
Switching to frames in frozen code results in an error message box. This is annoying when quickly switching between frames via the mousewheel. With this PR, such frames (for example with file information `<frozen importlib._bootstrap>`) will be skipped.
> skip frozen frames when switching stack frames with mousewheel

- pyzo/core/editorTabs.py
Opening two different Python scripts that are located on a WebDAV mapped drive in MS Windows at the same time does not work in Pyzo.
After having openend the first file and then opening the second file, Pyzo thinks that the second file is already opened and switches to the editor of the first file.
This is because Python command `os.path.samefile(fp1, fp2)` does not work for files located on WebDAV mapped drives:
https://github.com/python/cpython/issues/74665
**Solution**
If two files are detected to be the same file via an `os.path.samefile` equivalent, then some further checks are performed:
If the device id and the node id in the filestats are both zero and the filepaths are different, then the two files are not the same.
These checks are only performed …
> add workaround for WebDAV mapped drives in opened-file-detection

- pyzo/core/shell.py
Double clicking a filepath in the shell did not work for warning exceptions.
For example when double-clicking "tmp" in the line
`/tmp/aa.py+5:3: SyntaxWarning: invalid escape sequence '\s'`
Pyzo would try to open file "/tmp/aa.py+5:3: SyntaxWarning: invalid escape sequence".
After this commit, double-clicking will open the correct file "/tmp/aa.py" at line 8.
> implement file opening on doubleclick in shell for warnings

- pyzo/core/shell.py
Double clicking on a filepath in the shell did not work for IPython-style tracebacks that are shown when the file is run as a script (with IPython active):
`File /tmp/aa.py:8, in myfunc1()`
So I did an overhaul of the whole function that handles the doubleclick on filenames.
The editor now gets the focus as well.
> rework file opening on doubleclick in shell on filepath

- pyzo/codeeditor/extensions/calltip.py
This PR will change the behavior so that calltips are automatically closed/hidden when the textcursor is moved to another line.
> close calltip when moving the textcursor to another line

- pyzo/core/shell.py
Lines larger than 1024 characters, that were split into shorter lines of 80 characters each, will now be joined again when selecting the text for copying via clipboard or drag'n'drop.
This is useful when copying longer values that were printed to the shell, for example the output of:
`>>> import os; os.environ`
Shortened lines now have a `SHORTENED_LINE_MARKER` before the `\n` so that these extra line breaks can be identified and removed again. I selected a "zero width space" unicode character for that. If a user intentionally prints such characters, they might confuse the method used for rejoining the lines in some cases.
The marker can be temporarily changed in Pyzo's Logger tool by executing, for example:
`pyzo.core.shell.BaseShell.SHORTENED_LINE_MARKER = ' \u200b\u2026'`.
> join broken lines in shell when copying them
