- pyzo/__init__.py
Now the windows have a wmclass and can be associated to
a program in linux
Fixes #396
It seems like Qt Applications having a different look when being run under root is quite typical
https://wiki.archlinux.org/index.php/qt#Theme_not_applied_to_root_applications
I might have accidentally deleted all the trailing whitespace in the file. If you don't want those modifications, I can create a new pull request.
> Passed sys.argv to the QApplication function

- MANIFEST.in
This PR improves the current sdist to include additional files and documentation necessary to package the application downstream. Right now, the default provides just the public module and associated `setup.py`, but having the README, RELEASE_NOTES and metadata files are also desirable. I have added the `pyzolauncher.py` script so the tarball on PyPI can also be executed standalone.
Let me know if you have further comments.
Cheers,
Ghis
> Improve default sdist with explicit MANIFEST.in file.

- pyzo/codeeditor/base.py
Editor window will scroll (center the cursor) only when the cursor moves close to the window border.
> Reduce scrolling while stepping in the debugger

- pyzo/tools/pyzoWorkspace.py
By piggybacking the "hide function" menu item. I use a dictionnary to
map what I want to hide to the relevant menu item. A bit
overengineered, but can be extended.
> Attempt at hiding methods

- pyzo/core/shellInfoDialog.py
- pyzo/pyzokernel/guiintegration.py
- pyzo/pyzokernel/interpreter.py
This PR adds PySide2 GUI integration
PySide2 is not yet very widespread, but is AFAIK the only LGPL solution for Qt on Python >3.4.
This PR was tested on Windows, PySide 2 installed as described here:[Compiling PySide2 from source](https://fredrikaverpil.github.io/2016/08/17/compiling-pyside2/). Furthermore, one may need to copy the Qt binary files to the Python working directory as described here:[Deploy an Application on Windows](http://wiki.qt.io/Deploy_an_Application_on_Windows)
> Added GUI integration support for PySide2

- Info.plist
Small addition of 2 lines, but makes Pyzo's text crisp on high DPI/Retina screens for macOS, even if Pyzo's images aren't at the moment.
> Better high resolution (Retina) support on macOS

- pyzo/core/shell.py
A line '\r blabla' should result in the previous line being wiped clean. Before this PR, only 'blabla \r' would be handled correctly (i.e. the next line would be printed on top of the 'blabla' line). With this change, also messages starting with carriage return will overwrite the previous line in the shell.
> correctly handling messages that *start* with carriage return

- pyzo/core/main.py
- pyzo/core/menu.py
- pyzo/core/shellStack.py
- pyzo/resources/translations/pyzo_fr_FR.tr
A few strings needed a "translate" call so that they could be translated. There is also the string in "core/splash.py" and some others (line 673 and more) in "core/shellStack.py", but I'm not sure how to do it since they have three double quotes!
I also fixed a few minor things in the French translation.
> Made a few more strings translatable in menu,shell,main.

- pyzo/core/menu.py
I have implemented the use of %run -i, when the shell is an ipython shell
> Use %run -i to run script when ipython console is used

- pyzo/core/main.py
Allowing shell window to float is useful in dual screen mode
> Allows the Shell window to float (like other tools)

- MANIFEST.in
Otherwise, `doc/Makefile` is missing from the source tarball.
> Fix inclusion pattern for the docs

- pyzo/__init__.py
This allows somebody who deploys pyzo to a multiuser environment to create a ```pyzo/resources/siteConfig.ssdf``` file the content of which will override the defaultConfig but in turn be overridden by the user configuration file.
> Allow for a site-wide config file

- pyzo/pyzokernel/magic.py
Some of my students have the unpalatable habit of typing a space between the name of a function and the parenthesis, ie. ```open ("/tmp/somefile")``` instead of ```open("/tmp/somefile")```. I think this is bad style, but it is definitely syntactically valid as per [python's lexical analysis rules](https://docs.python.org/3/reference/lexical_analysis.html#whitespace-between-tokens).
The problem is that there is also a magic command with name ``open`` and pyzo gives it precedence when this word is followed by a space. This leads to very strange error messages like
```
Could not determine file name for object "("/tmp/essai")".
```
or even
```
Error in handling magic function:
invalid syntax (<string>, line 1)
line 347 in /opt/yann/pyzo-4.4.2/source/pyzo/pyzokernel/magic.py
line 70 in …
```
> Solve confusion between open magic command and open python function

- pyzo/core/editorTabs.py
When using a portable installation (appdatadir = settings) it is often the case that file paths are not found on the next run, due to the program being executed on a different machine.
This results in an inconvenient series of error dialogs at startup.
This patch will first check existence of files and open only the available ones. If no file is found at all, a new file is created.
> Do not show file not found error dialog at startup

- pyzo/tools/pyzoHistoryViewer.py
History Viewer now auto scrolls to the bottom of the list when new commands are entered in the shell instead of "getting stuck" at the beginning of the list, with newer commands disappearing out of the window.
Before:
After:
In addition, history viewer now scrolls to the bottom automatically when starting the program.
I'm at wit's end as to whether this is a bug or a feature working as intended. Personally I find it frustrating that I have to keep scrolling down the list manually to copy the latest commands from the shell to my editor. I'm anxious to know whether I am the only one with this issue!
In addition, if it _is_ a UI bug, I do not know whether it is only encountered on some configurations or under specific back-ends (i.e. Pyside/pyqt4/pyqt5). I encountered the bug both in a …
> Bug or feature?: History Viewer auto scroll fix

- pyzo/core/editor.py
When commenting a code (using e.g. Ctrl+R):
[4 spaces]some_text_1
[empty line]
[4 spaces]some_text_2
I got:
[4 spaces]# some_text_1
[empty line]
[3 spaces]## some_text_2
Using the modificated code, I get:
[4 spaces]# some_text_1
[4 spaces]#[1 space]
[4 spaces]# some_text_2
As this is my first pull request I want to say big thanks to almarklein and all other contributors for this great Python IDE.
> fix block commenting when having empty lines

- pyzo/codeeditor/extensions/behaviour.py
>     Add auto removal of ), ], } if (, [, { are removed using backspace, and if they are side by side ( i.e (), [] and {} ).
>     Improve auto-close that prevented the addition of the closing braces and brackets.
Hello! I improved a bit the automatic insertion system of brackets. The previous one was sometime frustrating, because it didn't auto-close brackets correctly in some situations, like this one:
_Auto-close before:_
_Now:_
I also added a system to auto remove brackets:
_Auto removal of brackets:_
Now it behaves more like some others editors (like sublime text).
Please note that I'm pretty much a noob in development, so please tell me if there is any problem.
> Improve automatic insertion of braces and brackets

- pyzo/pyzokernel/magic.py
Re my issue #566 : students mistyping `=!` in the console just cannot understand what is going on due to it being interpreted as the assignment of the result of IPython's shell invocation.
This adds a quirk to the management of magic features of the console to abort interpretation when `=!` is encountered without intervening spaces. I am using Python's tokenization for this to avoid problems with `=!` being actually part of eg. a string literal.
I catch it early ; maybe too early ? I did not check for inconsistent behaviour when `=!` would be a (typo or non-typo) part of an actual magic command.
I just printed error messages ; there may be a better utility function for this (to display as error).
> Preventing IPython's interpretation of =! typo in console

- pyzo/core/menu.py
Turns out the Advanced Settings dialog is completely broken ! There is a typo in the code that prevents any actual setting update. Also made help text word-wrap and be translatable, and making the dialog resizable by the user.
> Fixing advsettings

- pyzo/codeeditor/manager.py
- pyzo/codeeditor/parsers/__init__.py
- pyzo/codeeditor/parsers/python_parser.py
- pyzo/core/shell.py
- pyzo/core/shellInfoDialog.py
- pyzo/resources/defaultConfig.ssdf
Currently, there is a generic Python parser that has the reunion of the keywords of Python 2 and Python 3. 
In fact this parser is used more frequently than either the specific Python 2 and Python 3 parser due to the detection process.
This is problematic because there does not actually exist a generic Python language. Especially, this generic-python parser will typeset ``print`` as a keyword (like Python 2) although it really is just a function in Python 3. This is misleading for students, who sometimes struggle to understand the difference between a keyword and an identifier, as well as between the semantics of ``print`` and ``return``.
My proposal is to explicitly label such cases as _ambiguous_ rather than _generic_, to try to limit such cases, and, at least in the case of a newly …
> Disambiguate Python 2 and 3

- pyzo/codeeditor/extensions/appearance.py
- pyzo/core/baseTextCtrl.py
- pyzo/core/editor.py
- pyzo/core/menu.py
- pyzo/core/shell.py
This shuffles options management a little so that ShowWhitespace and HightLightMatchingBracket are also applied to shells, not only code editors.
This adds support for highlighting matching brackets in shell : in fact the heavy work (parsing the line to get tokens) was already done, the tokens were just not stored in the block's userData.
> ShowWhitespace and HighlightMatchingBracket options for shell

- pyzo/codeeditor/parsers/python_parser.py
- pyzo/core/shell.py
- pyzo/core/shellInfoDialog.py
- pyzo/resources/defaultConfig.ssdf
Post- #613 tweaks.
Remove reference to `pyzo` in `codeeditor` (we try to keep that part free from Pyzo logic). This means we cannot use Pyzo config here ...  we could move the default disambiguation somewhere else, but I do not think that is necessary; you're right, ppl should use Python 3. And those who use Python 2, can use a shebang to mark the code at Python 2. We might implement/improve `AmbiguousPythonParser.disambiguate()` at some point to detect Python 2 files, if needed.
Instead of letting the user mark interpreters as either Python 2 or Python 3, we can just check the version info that we get from the kernel.
> Tweaks after #613

- pyzo/core/menu.py
- pyzo/core/pdfExport.py
Hello!
I improved the pdf export system, which was very basic.
Now, there are some options, such as page orientation, enable/disable syntax highlighting, and lines numbers have now a grey background. There is also a preview.
I tried to add options for margins, but unfortunately it seems there is a bug with Qt:
https://stackoverflow.com/questions/49351391/qprinter-margins-under-py3-and-pyqt5
https://bugreports.qt.io/browse/QTBUG-32987
Also, I wanted to add an option for page number, but there is no simple way to change this (AFAIK).
This is probably far from perfect, so please tell me if there is any problem (bad function/variable name, or anything else).
> Improve pdf export

- pyzo/__init__.py
- pyzo/core/about.py
- pyzo/core/menu.py
- pyzo/util/paths.py
On Unix-like systems, pyzo config folder is located directly inside home folder of users, which is a bit annoying: https://0x46.net/thoughts/2019/02/01/dotfile-madness/
Pyzo should use $XDG_CONFIG_HOME to store configuration, and $XDG_DATA_HOME to store data (e.g. history). (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
I used QStandardPaths from Qt to get those paths, this should work on any system (MacOs, Windows...).
For retro-compatibility reasons, pyzo will use old its folder if it exists.
I don't really understand the purpose of pyzo_dirs2() and pyzo_dirs(). What path should they use ?
> Use standard folders for data and config

- pyzo/core/editorTabs.py
- pyzo/core/menu.py
- pyzo/core/shellStack.py
- pyzo/resources/defaultConfig.ssdf
- pyzo/tools/pyzoFileBrowser/__init__.py
- pyzo/tools/pyzoHistoryViewer.py
- pyzo/tools/pyzoInteractiveHelp.py
- pyzo/tools/pyzoLogger.py
- pyzo/tools/pyzoSourceStructure.py
- pyzo/tools/pyzoWebBrowser.py
- pyzo/tools/pyzoWorkspace.py
Margins between gui elements editor, shell, logger and plugins are consistent as shown in the image below. New config option added: margins=[4,4,4,4].
> Unify margins between gui elements editor, shell and plugins #627

- pyzo/core/menu.py
should fix #638
Bonus: with Qt >= 5.1 the context menus display their tooltips, too
> let QMenu display its tooltips

- pyzo/pyzokernel/introspection.py
Fix : When exploring a dict in workspace, the line relevant to a dict key displays the key itself instead of the value associated to that key.
Also : display dicts as ``<dict with {:d} keys>`` instead of the 77 first chars of its representation.
> Bugfix workspace dict

- pyzo/core/menu.py
After Factory Defaults, it would be nice to have option to overwrite an existing (Python) shell settings with backup shell settings.
> Overwrite an existing shell settings with backup shell settings.

- freezeScript.py
- freezeScript2.py
Renaming `_settings` folder to `settings` has no *portable* effect if there isn't a `pyzo` subfolder.
> Portable settings folder

- pyzo/codeeditor/base.py
- pyzo/codeeditor/parsers/python_parser.py
- pyzo/codeeditor/parsers/tokens.py
- pyzo/codeeditor/style.py
- pyzo/core/themeEdit.py
This creates a new token type, IllegalToken, to represent characters that may not appear in Python identifiers (currently, only nbsp will be parsed as such). The default style of this token type is a reddish background.
Consequently, this also fixes some bugs related to background color for characters in editors (the property was not applied !). However, the interaction between styles and the theme editor when adding a new style category remains a mystery for me.
This also fixes an anomalous yet documented behaviour of QtPlainText.toPlainText where nbsp are replaced by regular spaces : this affected us on saving the document.
> Highlighting non-breakable spaces

- pyzo/pyzokernel/introspection.py
- pyzo/tools/pyzoInteractiveHelp.py
Contrary to the shell's ``help`` builtin, Pyzo's interactive help will not display the signatures of functions.
This is due to :
- the interactive help not doing anything with the signature when it gets one ;
- the introspection module erasing the signature from its response on builtin functions.
According to the comments, the latter is done on the assumption that builtin functions have their signature at the beginning of their docstring. This is true for eg. ``numpy.zeros`` but false for ``open``.
There is some code in the help tool to detect the signature in the docstring and displaying it nicely ; I added a fallback code where we just use the signature given by the introspection.
> Displaying signatures in interactive help

- azure-pipelines.yml
- freeze/freezeScript.py
- freeze/installerBuilderScript.iss
- setup.py
* Only build windows installer for 64bit (because the 32bit version seems to be broken).
* Make that 64bit installer install in `program files`, not `program file x86`.
* Try to fix #678 ... no luck so far. Ideas:
* build the Linux version on Travis? (and then figure out how to push the artifact *sigh*)
* build on another vm?
* use the default python on the vm instead of using the `UsePythonVersion` task.
> Build tweaks

- pyzo/codeeditor/extensions/autocompletion.py
- pyzo/core/baseTextCtrl.py
- pyzo/resources/defaultConfig.ssdf
Fixes #689 
Currently showing the popup after 3 chars. Seems to work.
**How to manage the setting ?** Should AutoCompletion refer directly to the value of pyzo setting, or should make the setting separate from AutoCompletion::__autocompleteMinChars ? This would require an update mechanism to propagate a new setting value.
Currently the interactive help still updates from the first char, which is odd. **Should the interactive help also "listen" to the pyzo setting ?** I think it would be to mundane to make a setting for the number of chars before the popup and another for updating the interactive help.
> Starting autocomplete after some chars

- pyzo/__init__.py
Use-case: When I connect my 4K monitor and set it up to be the only monitor, the GUI is scaled correctly and fonts look crisp.  (The 16x16 icons look fuzzy, but that's a problem for another day.) When I set the monitor up as an additional display, everything looks a bit fuzzy. What matters is the situation when Pyzo starts up. Using one monitor, then starting Pyzo, then switching to two monitors, will keep Pyzo in a good state.
The problem is that Pyzo is currently setup to be system-level aware. Search for "dpiawareness" on https://doc.qt.io/qt-5/highdpi.html. This PR fixes that.
> Make hidpi work for multiple monitors

- pyzo/__init__.py
With #696 the behavior with high resolution monitors has much improved. But I recently found Pyzo in a state where half the application was in high-res mode, and some was not. It was as really odd: within the same list widget, some items where smaller than others. I should have made a screenshot. The error persisted even after restarting Pyzo.
My guess is that it is related to unplugging a high-res monitor and plugging in another, or something like this.
Anyway, I found that adding this lines fixes it:
```py
ctypes.windll.shcore.SetProcessDpiAwareness(1)   # <-- added
ctypes.windll.shcore.SetProcessDpiAwareness(2)
```
My suspicion is that with the first line it will pick up the global dpi setting, and then with the second line it will refine to the current monitor. Doing only the latter …
> Improve hidpi behavior

- pyzo/core/commandline.py
- pyzo/yoton/channels/channels_reqrep.py
deprecated isAlive() has been removed in Python-3.9
solves https://github.com/pyzo/pyzo/issues/713
> replace deprecated isAlive() per is_alive()

- pyzo/core/menu.py
Removes some clutter. The use-case for terminating a shell without closing it are very slim ...
> Disable button to terminate shell but leave it open

- pyzo/codeeditor/__init__.py
- pyzo/codeeditor/extensions/behaviour.py
- pyzo/codeeditor/extensions/calltip.py
- pyzo/core/baseTextCtrl.py
Closes #711 (and its duplicate #622)
In some places in the code we use `event.key` to see what character was written. But this is wrong, since this refers to the key, not the actual character. Most notably this breaks things when the auto-bracket-close function is enabled.
* Fix auto-close brackets and auto-close quotes.
> Better support for non-english keyboard layouts

- azure-pipelines.yml
- pyzo/__init__.py
This makes the CI/CD builds run on Python 3.9 and sets the `QT_MAC_WANTS_LAYER` environment variable to make Qt (and thus  Pyzo) work on MacOS Big Sur. Also bumps the version number, because I provided the MacOS build artifact for testing, and giving it a different version number helps differentiate between versions.
> build on 39

- pyzo/core/icons.py
- pyzo/core/shell.py
- pyzo/core/shellStack.py
- pyzo/pyzokernel/guiintegration.py
- pyzo/pyzokernel/interpreter.py
- setup.py
MacOS's activity monitor also shows the "energy impact", and it showed that Pyzo in idle mode is more hungry than other applications. These measures reduce that quite a bit. The kernel (with no GUI or asyncio GUI) seem to be about 8x leaner, and the IDE itself about 2x.
This also uses the new asyncio gui integration, which I worked on earlier, but never applied yet.
> Tweaks to make Pyzo consume less power when idle

- pyzo/pyzokernel/interpreter.py
On Windows, IPython is not loaded from version 8.x.x and the console throws the error:
> 'IPython.utils.io'` has no attribute 'IOStream'
See [issue #796](https://github.com/pyzo/pyzo/issues/796).
So far the fix is working without problem.
> Bug IOStream from IPython 8.x.x

- pyzo/core/editorTabs.py
The error may look a bit scary, and is not really necessary on a fresh start. Plus it prevents the error message described in #804: on frozen Pyzon on Windows, on restart it tries to open a nonexisting pyzo.exe.
> Dont show an error dialog when failing to load files on startup

- pyzo/yoton/channels/channels_base.py
- pyzo/yoton/misc.py
notifyAll() deprecated and replaced with notify_all() in Python 3.10
> Compatibility Python 3.10

- pyzo/pyzokernel/introspection.py
As described in #816, some special cases will cause the Pyzo introspection to iterate infinitely for special class objects, and this can result in steadily rising memory usage.
The example in the issue can be broken down to the code
```
class Query:
def __init__(self):
print('__init__')
def __getattr__(self, item):
print('__getattr__', item)
return self
def __getitem__(self, item):
print('__getitem__', item)
return
Q = Query()
```
When running this code in Pyzo, pyzokernel/introspection.py will see a new global variable "Q" and run "dir2". Then "dir2" and "storeInfo" will execute `hasattr(val, "__array__")` etc. and come to the conclusion, that the object is an array -- because the Query class will have any attribute that is looked up (see `__getattr__`). Still in "storeInfo", the line …
> fix introspection infinite iteration for special cases

- pyzo/codeeditor/base.py
- pyzo/codeeditor/extensions/appearance.py
- pyzo/core/menu.py
- pyzo/core/themeEdit.py
- pyzo/pyzokernel/introspection.py
- pyzo/qt/QtCore.py
- pyzo/qt/QtGui.py
- pyzo/qt/QtHelp.py
- pyzo/qt/QtWidgets.py
- pyzo/qt/enums_compat.py
In Pyzo we access a lot of enum values via the object, but since pyside6.4 these are only available on the class, or via the enum field. Example:
* Given `option = QTextOption()`
* We have `QTextOption.Flag.ShowTabsAndSpaces`
* We have `option.Flag.ShowTabsAndSpaces`
* We have `QTextOption.ShowTabsAndSpaces`
* We no longer have `option.ShowTabsAndSpaces`
It's tedious and error-prone to update all cases, so we fix it at the core. Similar how this seems to be fixed for PyQt5 in qtpy.
> Fix Enums on pyside 6.4

- pyzo/core/commandline.py
- pyzo/util/interpreters/__init__.py
Closes https://github.com/pyzo/pyzo/issues/814
Makes pyzo consider a user-defined python exe file without having to write it down manually in the file explorer.
This comes in handy for NixOS users because they'll be able to make pyzo automatically propose a specific python executable from the nix store, which is a better UX than having to directly deal with the hash-looking paths of the store...
> Introduce PYZO_DEFAULT_SHELL_PYTHON_EXE env-var

- pyzo/core/editor.py
* Fix that the reload is done. It was ignored, because the working of enums changed in some Qt implementation :/
* Avoid bug where the editor had focus but also kinda did not? (could edit text but cursor was not blinking).
> Fix reload when file changed externally

- pyzo/core/kernelbroker.py
- pyzo/core/shellInfoDialog.py
When editing or adding a shell configuration using the dialog, the text box "environ" shows the following text instead of an empty string (unless modified by the user):
```
EXAMPLE_VAR1=value1
PYZO_PROCESS_EVENTS_WHILE_DEBUGGING=1
```
But these variables never appear in os.environ -- the shell config ignores the text because it is a kind of placeholder text but implemented as normal text data. This has caused some confusion, as placeholder texts in other fields in the shell config dialog are implemented as proper placeholder texts (grayed out and vanishing when entering text).
This pull request changes the environ text field to have a proper placeholder text.
The old implementation allowed for easy inserting the useful environment variable `PYZO_PROCESS_EVENTS_WHILE_DEBUGGING=1` by just …
> have proper placeholder text for environ in shell config dialog

- pyzo/codeeditor/extensions/appearance.py
Apparently, the menu command "Shell -> Clear all {x} breakpoints" got broken at Pyzo v4.4.
This fix restores its function.
> fix breakpoint removal (Shell -> Clear all {x} breakpoints)

- pyzo/core/shell.py
Double-clicking on a file name in the shell text, for example in the traceback message
`File "C:\temp\test.py", line 5, in <module>`
will open the file in an editor tab and move the cursor to the specified line number.
But for new, unsaved files with pseudo filenames "<tmp 1>" etc., this does not work.
The proposed change will make it possible to jump to lines of such new, unsaved files.
> Allow <tmp 1> etc. as filename when double-clicking text

- pyzo/pyzokernel/interpreter.py
Problem:
On a Windows operating system, breakpoints do not work when executing a cell, as if they were not present. But when excuting the whole file or only the top cell, breakpoints work normally. And when executing any cell in a new, unsaved file ("<tmp 1>" etc.), breakpoints works normally as well.
Cause:
The python debugger pdb uses a filepath line-number combination as a key in its breakpoints data structure, where the filepath must be the canonical form. When setting the breakpoint, the debugger gets the correct canonical form of the filepath, but when executing a cell (or several selected lines), the code segment is compiled first with the normal form of the filepath, but not the canonical one. For example, filepath "C:\temp\test.py" will be different from its canonical form …
> fix breakpoints during cell execution on MS Windows

- pyzo/core/shellStack.py
Problem:
After entering the debug mode and switching stack frames, the cursor does not jump to the proper line in the code editor when the code is in a new, unsaved file (e.g. "<tmp 1>").
Cause:
Function "debugFocus" in class "DebugStack" (shellStack.py) sees a filename starting with "<" as invalid and will not even try to look up the correct code editor tab. But when calling "pyzo.editors.loadFile(filename)", it is absolutely ok to pass "<tmp 1>" as filename, and this returns the correct editor tab.
Fix:
Removing the rule to ignore filenames starting with "<" solves the problem.
> fix missing cursor update when switching stack frames

- .github/workflows/cd.yml
- freeze/pyzo_freeze.py
In https://github.com/pyinstaller/pyinstaller/pull/7180#issuecomment-1415721750 a tip for the `codesign` syntax was given:
```
codesign -s - --force --all-architectures --timestamp --deep --entitlements /path/to/entitlements-file.plist /path/to/bundle.app
```
This works, and MacOS stops complaining about the app being broken or modified. But it still says it's untrusted, and requires right-clicking to open the app.
For proper code signing, you need to:
* Create an Apple developer account ($100 per year)
* Create a certificate with that account
* Setup Github Actions to sign with that certificate.
* Setup Github Actions to Notarization the app (verify that it's clean).
For detailed instructions, see https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using- …
> Signing of the app for macos

- pyzo/core/baseTextCtrl.py
This PR enables autocompletion when typing string literals (and similar objects), for example:
typing `' '.j` wll suggest `join`
typing `b'test'.d` wll suggest `decode`
And this PR also includes a minor code clean-up:
`isinstance(token, (Tokens.IdentifierToken, Tokens.KeywordToken))`
is the same as
`isinstance(token, Tokens.IdentifierToken)`
because `Tokens.KeywordToken` is a subclass of `Tokens.IdentifierToken`
> enable autocompletion for string literals

- pyzo/qt/QtGui.py
- pyzo/qt/QtWidgets.py
- pyzo/tools/pyzoFileBrowser/tree.py
added some further fixes for PyQt6 support
and a hint for a special case in PySide6:
When wanting to use special PySide6 features "snake_case" and/or "true_property", then use PySide6 >= 6.4.2 because
```
from PySide6 import QtGui, QtCore, QtWidgets
from PySide6.QtWidgets import QApplication
backup_QApplication_hijacked = QApplication.__new__
from __feature__ import snake_case, true_property
assert backup_QApplication_hijacked is QApplication.__new__ # fails on PySide6 < 6.3.0
```
relevant fixes in the PySide6 project:
https://code.qt.io/cgit/pyside/pyside-setup.git/tree/doc/changelogs/changes-6.3.0
[PYSIDE-1702] snake_case handling now does explicitly not touch user defined classes.
https://code.qt.io/cgit/pyside/pyside-setup.git/tree/doc/changelogs/changes-6.4.2
[PYSIDE-1019] A callback …
> fixes for PyQt6 and PySide6 support

- pyzo/pyzokernel/interpreter.py
This PR will fix the following problem:
When using the following startup code in the shell configuration (startupScript -- Code to run at startup)
```
print(1)
print(2)
print(3)
print(4)
````
and creating the shell, then the output is
```
1
2
Python 3.11.1 (main, Jan 16 2023, 22:41:20) on linux (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT6.
Type 'help' for help, type '?' for a list of *magic* commands.
File "<console>", line 1
print(3)
^
SyntaxError: multiple statements found while compiling a single statement
```
> allow multiple statements in shell startup code after gui initialization

- pyzo/core/menu.py
- pyzo/core/pdfExport.py
- pyzo/qt/QtPrintSupport.py
PDF export works now across PyQt and PySide with Qt5 and Qt6. And page orientation can be set to landscape again.
worth mentioning:
Opening the PDF export dialog when running Pyzo with PySide2 Qt bindings in Linux caused a segmentation fault. Changing `PdfExport().exec()` to `PdfExport().exec_()` solved that. All other dialogs (subclasses of `QtWidgets.QDialog`) already used the unproblematic `.exec_()` call.
> fix pdf export

- freeze/boot.py
- pyzo/__init__.py
As described in #859, starting a second instance of Pyzo to open a file will show a cmd console window and an error message box in MS Windows.
The console window and the error message box seem to be opened because an exception is raised after successfully opening the file. This exception is of type `SystemExit` and caused by the command
https://github.com/pyzo/pyzo/blob/ebb7df8922af8e15eac102e8fa4a35bfa143869a/pyzo/_start.py#L77
which is just called to gracefully close the second Pyzo instance.
> prevent error message box when running a second Pyzo instance to open a file

- pyzo/core/main.py
Restarting Pyzo in MS Windows, for example via "File --> Restart Pyzo", causes errors when there is a space in Pyzo's path or in the path of the python file to open.
An "Error loading file" message box appears because sys.argv is split.
Logger window in Pyzo before the restart:
```
>>> sys.argv
['C:\\Program Files\\pyzo\\pyzo.exe']
```
Logger window in Pyzo after the restart (without the patch):
```
>>> sys.argv
['C:\\Program', 'Files\\pyzo\\pyzo.exe']
```
The suggested workaround, consisting of quoting all argument list entries, is only required for MS Windows, but not for other operating systems.
> fix Pyzo restart in MS Windows with spaces in paths

- pyzo/qt/QtGui.py
When running Pyzo in PyQt6 the menu "View --> Font" did not work because PyQt6 does not allow `QtGui.QFontDatabase()` anymore (but PySide6 still does).
> fix QFontDatabase compatibility for PyQt6

- pyzo/codeeditor/extensions/appearance.py
The new code will properly highlight the matches of the selected text even when they are line-wrapped.
before applying the patch:
after applying the patch:
> fix matching selection highlighter for line-wrapped occurrences

- pyzo/core/themeEdit.py
In the theme editor dialog ("Settings --> Edit syntax styles..."), clicking a code element in the preview text editor widget normally automatically puts the focus on the color input widget for the clicked syntax element type.
This did not work when running Pyzo with PySide2, PySide6 or PyQt6 (instead of PyQt5).
This patch will restore this focussing functionality for all four Qt wrappers.
> fix themeEdit focussing for PySide2, PySide6 and PyQt6

- pyzo/core/pyzoLogging.py
changes:
- year-month-day instead of day-month-year
- only one space between timestamp and message instead of two
- code clean-up
> clean-up logging timestamp preamble

- pyzo/core/assistant.py
- pyzo/core/editorTabs.py
- pyzo/core/pdfExport.py
- pyzo/resources/defaultConfig.ssdf
- pyzo/tools/pyzoFileBrowser/importwizard.py
This PR will allow for using non-native file dialogs (Qt widgets based) instead of the operating system provided ones.
To enable these non-native file dialogs, users have to change the "advanced -> useNativeFileDialogs" setting in the "Advanced Settings" dialog from default value 1 to 0.
One of the use cases is to avoid specific errors on MS Windows -- I will write an issue for that later and mention it in this PR.
> add optional non-native file dialogs

- freeze/pyzo_freeze.py
- pyzo/qt/QtWidgets.py
As far as I can tell, Pyzo does not use and does not need the QtOpenGLWidgets.
> remove QtOpenGLWidgets

- pyzo/tools/pyzoLogger.py
Without this patch, the Pyzo Logger displays for example
`Python 3.11. on linux - This is the Pyzo logger shell.`
instead of
`Python 3.11.0 on linux - This is the Pyzo logger shell.`.
> fix truncated version info string in pyzo logger welcome message

- pyzo/core/editorTabs.py
The old `QtCore.QRegExp` from Qt4 (and Qt5) does not work anymore in Qt6.
The new `QtCore.QRegularExpression` works in Qt5 and Qt6.
> fix regex search in editor for Qt6

- pyzo/resources/themes/dark.theme
- pyzo/resources/themes/default.theme
- pyzo/resources/themes/scintilla.theme
- pyzo/resources/themes/solarized_dark.theme
- pyzo/resources/themes/solarized_light.theme
In the syntax/theme editor, style entry "Syntax.illegal" the color entry widgets are all empty for all themes (including the default theme), because in the *.theme files, the entry "syntax_illegal" was missing.
This missing entry has already been mentioned some time ago in #698.
This PR adds the missing lines in the themes files.
> add missing style entry for Syntax.illegal

- pyzo/core/editorTabs.py
The value for the "Auto hide" checkbox is read from the config file but was never saved back to it unlike the other checkboxes.
With this PR, the state of the "Auto hide" checkbox will be saved.
> save "Auto hide" value in editor search dropbox

- pyzo/core/editorTabs.py
In my opinion, the borders around the search dropbox are a waste of space.
With this PR, I can see ca. 1.5 text lines more in the editor when the search dropbox is visible.
> reduce search dropbox margins

- pyzo/pyzokernel/guiintegration.py
I just stumbled upon this:
Pyzo still supports Python 2.7 shells/kernels (after correcting one line with this PR).
@almarklein:
In my opinion we could drop Python 2.7 support (as well as Qt4 support) to modernize the codebase.
What do you think about that?
> python 2.7 compatibility

- freeze/frozen_libs.txt
- pyzo/pyzokernel/interpreter.py
- pyzo/qt/__init__.py
- pyzo/util/__init__.py
- setup.py
Currently, there are two use cases for converting a string, like "123.45ew6.7x.dev8", to a comparable tuple, like (123, 45, 7).
1. `pyzo/pyzokernel/interpreter.py`
The version comparison is just to check if the macOS version is >= 10.9.
Before this PR, `distutils.version.LooseVersion` was used, but `distutils` is not available anymore in Python 3.12. See [PEP 632](https://peps.python.org/pep-0632/) and the [release notes](https://www.python.org/downloads/release/python-3120b2/) for details.
2. `pyzo/qt/__init__.py`
The version comparison is to check macOS and Qt versions.
Before this PR, the external package `packaging` was used for this (and only for this).
With the own implementation, pyzo has no more external dependencies, except `dialite` and a Qt binding.
The new function …
> replace version string parser with own implementation

- setup.py
According to `pyzo/__init__.py`, the minimum required Python version is 3.6.
> update required python version

- pyzo/core/icons.py
- pyzo/core/main.py
The green arrow in the Pyzo app icon (when a shell was busy) was only added for the lowest resolution icon with 16x16 pixels.
Because of this, at least in Linux and MS Windows, there was no "running" overlay visible for larger icons.
This PR adds the arrow to all resolution pixmaps of the icon.
> fix "running" icon with green arrow for all icon resolutions

- pyzo/_start.py
- pyzo/core/assistant.py
- pyzo/util/interpreters/__init__.py
- pyzo/util/paths.py
I encountered the following problem on different computers with MS Windows 10:
After installing and running Pyzo the first time, the user confirms the auto-detected pyzo interpreter or selects an individual one. But when closing Pyzo and starting it again, Pyzo does not remember the previous settings and the user has to configure everything again. After the second time, saving and loading the configuration works normally.
When starting Pyzo for the first time (i.e. no previously saved configurations found), Pyzo selects the following paths for the appdata and config by executing function `appdata_dir` in `pyzo/util/paths.py`. The results are:
```
[Logger] >>> pyzo.appDataDir, pyzo.appConfigDir
('C:/Users/user/AppData/Roaming\\pyzo', 'C:/Users/user/AppData/Local\\pyzo')
```
When starting …
> fix appconfig path on MS Windows and clean up code

- pyzo/core/editorTabs.py
- pyzo/tools/pyzoEditorList.py
When there are many tabs open in the editor, switching between them gets cumbersome. So I created a new tool:
The new EditorList is similar to the editor's tab widget.
Mouse Control
* right click on a list entry opens the context menu (the same as the tab's)
* double click on a list entry activates the corresponding editor tab (this is different, the tab saves on double click)
* double click below the last list entry opens a new editor tab
* middle click on a list entry closes the corresponding editor tab
* drag and drop to sort list entries, synchronized with the editor tabs
Keyboard Control
* ENTER or RETURN activates the selected editor tab
* DELETE will close the selected editor tab
* INSERT opens a new editor tab
* CTRL+SHIFT + UP/DOWN shifts the entry up/down (and the editor tab …
> add new tool "EditorList"

- .github/workflows/cd.yml
- pyzo/tools/pyzoFileBrowser/__init__.py
Also show a warning (in the logger shell) when pyside 6.5.1 or up is used on macos.
> Use pyside 6.4.4 for macos binary

- pyzo/core/main.py
The command server is stopped even when the user decides to not close Pyzo when asked for saving changes in editors.
**How to reproduce the problem**
- start Pyzo
- (optional: open the logger tool to see when the command server is stopped)
- create a new file and enter random characters --> editor tab icon turns red
- close Pyzo (e.g.: File -> Quit Pyzo)
- [Pyzo closes the command server, as indicated by output "Stopped our command server." in the logger widget]
- dialog pops up and asks to save modified file: Save | Discard | Cancel
- press Cancel
- command server is still stopped
- in MS Windows, opening a *.py file in the Windows Explorer will then start a new Pyzo instance instead of using the existing one
**Fix**
I changed the order in `closeEvent` so …
> fix pyzo closing cancellation

- pyzo/core/kernelbroker.py
We set `QT_MAC_WANTS_LAYER` as an env variable to get the Pyzo IDE running correctly on MacOS with high-res displays. However, since the env var leaks into the kernel, and it's apparently not neccesary on modern qt versions, qt gives a warning, which is confusing for users.
This PR prevents the env var from leaking into the kernel.
> Prevent warnings for qt on some macos's

- pyzo/core/codeparser.py
- pyzo/core/kernelbroker.py
- pyzo/tools/pyzoFileBrowser/proxies.py
- pyzo/util/bootstrapconda.py
- pyzo/yoton/channels/channels_reqrep.py
- pyzo/yoton/clientserver.py
- pyzo/yoton/connection_tcp.py
- pyzo/yoton/events.py
Changes:
- in kernelbroker.py there was a spelling mistake in `daemon` that created an unused attribute instead of setting the property
- `setDaemon()` is deprecated and therefore replaced by setting the property `daemon` depending on the interpreter version
> fix daemon threads

- pyzo/codeeditor/parsers/python_parser.py
- pyzo/core/menu.py
- pyzo/tools/pyzoInteractiveHelp.py
- pyzo/util/zon.py
When executing Pyzo from source with env variable `PYTHONWARNINGS=error` I got some errors about improper escaped strings in regular expressions. I fixed these and also cleaned up other re strings.
> fix and clean regular expressions

- pyzo/tools/__init__.py
When running "Tools -> Reload tools" in the menu, new tool py-files that were added after starting Pyzo were not detected. I changed the code to rescan both tool directories during reloading tools.
> re-scan tool directories when reloading tools

- .github/workflows/ci.yml
As described in #902, the pip dependency resolver suddenly decided to use a much older version 4.5.0 instead of the normally used 7.x.y, and this caused one build to fail. I changed the version to be at least 7.0.1 because that version was the minimum version used for the newest release and that version is also the highest version that still supports Python 3.6.
> require minimum version of pytest

- pyzo/core/shell.py
- pyzo/qt/__init__.py
From Qt5 to Qt6 the numeric values for `setFontWeight` changed:
Qt5 ... light: 25, normal: 50, bold: 75 ... see https://doc.qt.io/qt-5/qfont.html#Weight-enum
Qt6 ... light: 300, normal: 500, bold: 700 ... see https://doc.qt.io/qt-6/qfont.html#Weight-enum
To avoid Qt-version dependent value pairs I changed the code to use enum names (e.g. `QtGui.QFont.Bold`) instead of integers.
> use fontWeight enum names instead of integers

- pyzo/codeeditor/base.py
When working on improving the shell prompt I got some weird issues with text formatting.
The problem only occured with PySide 2 and PySide 6 but not with PyQt5/6.
It turned out that with PySide there were two different highlighter objects running at the same time instead of just the newer one of the derived class.
The object of `class CodeEditorBase(QtWidgets.QPlainTextEdit)` sets the default highlighter `Highlighter` (see pyzo/codeeditor/highlighter.py) during initialization.
The object of the derived `class BaseShell(BaseTextCtrl)` sets its custom highlighter `ShellHighlighter` (see pyzo/core/shell.py) to override the original highlighter.
Using PySide, the new highlighter is called additionally to the old one, and in some (reproducable) special cases, the new highlighter does not get …
> fix unremoved old highlighter after setting a new one

- pyzo/core/shell.py
- pyzo/pyzokernel/interpreter.py
When running a script that makes use of the Qt event loop and also using breakpoints, the breakpoints could be triggered by either
- the normal linear execution (while the shell is busy), or
- code executed in the event loop.
In the latter case, i.e. setting a breakpoint in a callback function, the shell's prompt does not change to the stack frame when triggering the breakpoint. One has to debug-step or press the RETURN key to update to the correct prompt text. The same happens, when leaving the debug mode.
While fixing this, I encountered a bug that caused wrong formatting, and fixed it -- see #905.
For the sake of completeness, this is the code I used to reproduce the problem and test the new behaviour:
```
from PySide2 import QtGui, QtCore, QtWidgets
class …
```
> fix shell prompt for debugging with stack frames

- pyzo/core/editorTabs.py
When searching for whole words (with RegExp disabled), the needle was not escaped before this PR.
> escape needle when searching for whole word in editor

- pyzo/pyzokernel/debug.py
Since Python 3.7 there is a built-in function `breakpoint()` that opens a text based debugger at the place it was called.
Executing this command in the Pyzo shell also brings up the text based debugger.
I changed the code so that the `breakpoint()` command will use the debugger toolbar of the Pyzo GUI, the same way as breakpoints do, i.e. without the text based pdb interface. In this custom implementation, the `PYTHONBREAKPOINT` environment variable has the same effects as in Python's default implementation.
As far as I have seen, using the `breakpoint()` command has the advantage of not slowing down the execution of the whole script, unlike when using Pyzo's graphical breakpoints. On the other hand, a `breakpoint()` command cannot be added or removed easily on the fly, e.g. in callback …
> add debugger integration for Python built-in breakpoint() function

- freeze/pyzo_freeze.py
- freeze/pyzo_package.py
- pyzo/core/editor.py
- pyzo/core/history.py
- pyzo/pyzokernel/interpreter.py
- pyzo/qt/uic.py
- pyzo/tools/__init__.py
- pyzo/tools/pyzoFileBrowser/proxies.py
- pyzo/tools/pyzoFileBrowser/tree.py
- pyzo/util/bootstrapconda.py
- pyzo/util/interpreters/__init__.py
- pyzo/util/zon.py
- pyzo/yoton/tests/count_lines_of_code.py
- setup.py
When executing Pyzo from source with env variable `PYTHONWARNINGS=error` I got many warnings because of files that were not closed (immediately). I changed the code to use the context manager whereever suitable, and I also cleaned up some mode and encoding arguments.
> use context manager for file access

- freeze/pyzo_freeze.py
The `distutils` package was removed in Python 3.12. I created a function that resembles the important part of it without external dependencies.
> replace deprecated distutils package

- pyzo/core/shell.py
This PR improves the performance of printing text in the shell.
Especially when printing many short lines, e.g. 10 characters per line, this results in a 5x speed-up.
```
import timeit
t = timeit.timeit("print(('a'*10 + '\\n')*20000)", number=10)
```
As a positive side-effect I also observed that the editor has a much better responsiveness. While the code that prints the text is (still) running, quickly typed characters do not show up immediately without this patch.
> improve shell printing performance for longer texts

- pyzo/core/editor.py
The operation "Edit -> Duplicate line" from Pyzo's menu normally duplicates the current line or the selected multiple lines in the code editor. But when having the cursor in the last line resp. when having multiple lines selected including the last line, the duplicated text was missing a part after the cursor/selection and also missing a new-line control character.
I fixed that with this PR.
> fix duplicate line operation in editor for last line

- pyzo/pyzokernel/debug.py
When I added the support for the built-in function `breakpoint()` (see #908), I forgot to only activate this for newer Python versions. Consequently, shells with Python versions < 3.7 crashed during start-up because of the missing `breakpointhook` attribute in the `sys` module. This PR will fix the problem by only activating `breakpoint()` for newer Python versions.
> activate breakpoint() only for Python >= v3.7

- pyzo/pyzokernel/pipper.py
Addendum to #919. Easier to just create a new PR for. cc @bdieterm
> In pipper: use bytes object instead list for pending stdout

- pyzo/_start.py
- pyzo/pyzokernel/start.py
Triggered by https://github.com/pyzo/pyzo/issues/901#issuecomment-1743858498, I checked the usage of `sys.argv` and made it such that if an OS would for some reason introduce args, Pyzo would be less likely to error on it.
> More reliable way to use argv

- pyzo/core/kernelbroker.py
- pyzo/yoton/events.py
Closes #746 
When I manually mangle the command into something invalid, everything is fine, because the process starts but produces errors over stderr. However, in certain cases the `Popen`  call can raise an exception, and this situation was not adequately covered. 
When the selected Python was invalid (e.g. a firewall or antivirus prevening access) this can cause Pyzo to hang because it keeps trying.
> Prevent Pyzo from hanging when starting kernel fails

- pyzo/tools/pyzoFileBrowser/__init__.py
- pyzo/tools/pyzoFileBrowser/browser.py
- pyzo/tools/pyzoFileBrowser/proxies.py
- pyzo/tools/pyzoFileBrowser/tasks.py
- pyzo/tools/pyzoFileBrowser/tree.py
> Filebrowser improvements

- pyzo/tools/pyzoFileBrowser/tree.py
When setting the filename filter in the "File Browser" tool to a suggested default value, e.g. `*.py *.pyw`, then no more *.py files are visible because in the new implementation, the filename only matches if all filter parts match (logical AND).
I reverted parts of #926 to get back the old behaviour (logical OR).
> fix filebrowser tool namefilter combination

- pyzo/codeeditor/parsers/c_parser.py
I have seen a warning about an invalid regex escape, so I fixed that.
And I also fixed some comments that got pushed down a line during the reformatting in #669.
> fix invalid regex escape in c_parser.py

- pyzo/pyzokernel/pipper.py
When "PYTHONWARNINGS=error" is added to the environ field of the shell configuration, the magic command `pip list` will print the following error after listing the packages:
```
Exception ignored in: <_io.FileIO name=18 mode='rb' closefd=True>
Traceback (most recent call last):
File "/tmp/pyzo/_internal/source/pyzo/pyzokernel/pipper.py", line 63, in pip_command_exe
subprocess_with_callback(print_, cmd)
ResourceWarning: unclosed file <_io.BufferedReader name=18>
```
I added a code line to close the buffered reader. This will not cause a warning resp. an error anymore.
> close subprocess pipe in pipper when finished

- pyzo/core/menu.py
- pyzo/resources/defaultConfig.ssdf
- pyzo/tools/pyzoFileBrowser/__init__.py
- pyzo/tools/pyzoFileBrowser/browser.py
This PR adds a menu entry for searching via the File Browser tool.
Similar to the normal search (Ctrl+F), the selected text in the editor is copied into the search field and the focus is moved to the search field.
This also works if no editor tab is open.
Default keyboard shortcut is Ctrl+Shift+F.
> add menu entry for search in file browser tool

- pyzolauncher.py
This PR will change pyzolauncher.py so that module "faulthandler" will not be used on MS Windows operating systems. This will prevent crashes when using the "File Browser" tool and native file dialogs when Pyzo is launched via pyzolauncher.py.
See issue #875 for details.
Deactivating the faulthandler on MS Windows is acceptable IMHO. When running Pyzo via the binary distribution (pyzo.exe) or via `python -m pyzo` there has also no faulthandler been activated.
> disable faulthandler in pyzolauncher.py in MS Windows to prevent crash

- pyzo/core/menu.py
Keyboard shortcuts for creating a new shell (Ctrl+1, Ctrl+2, etc.) stop working after just popping up the "Shell" menu (next to File, Edit, View, Settings).
The problem occurs in all tested operating systems (Linux, MS Windows) and all Qt wrappers (PySide2/6 and PyQt5/6).
**Analysis**
As far as I have seen, the menu action that includes the shortcut is stored twice:
First here: https://github.com/pyzo/pyzo/blob/31a00a62036bd3609c94ad42273c9ac5ba101358/pyzo/core/menu.py#L248
And then in the same function via the call to `pyzo.keyMapper.setShortcut(a)`: https://github.com/pyzo/pyzo/blob/31a00a62036bd3609c94ad42273c9ac5ba101358/pyzo/core/menu.py#L147
But when updating the shell entries
https://github.com/pyzo/pyzo/blob/31a00a62036bd3609c94ad42273c9ac5ba101358/py …
> fix shell keyboard shortcuts bug

- pyzo/core/editor.py
Issue #944 describes a special case where Pyzo autocomplete lookup gets stuck in an infinite loop when the parent class in a class definition is the same as the current class.
This PR fixes the bug by aborting the loop in that case.
> prevent autocomplete infinite loop for class lookup

- pyzo/pyzokernel/introspection.py
As described in issue #891, naming a variable "dir" will break autocompletion in Pyzo.
With this PR, the introspection for autocompletion will always use the built-in "dir" command, even when the user executed code such as `dir = 'northeast'`.
> always use built-in dir command for autocompletion introspection

- pyzo/core/kernelbroker.py
- pyzo/yoton/clientserver.py
This PR will prevent some warnings that are visible when running Pyzo from source with `PYTHONWARNINGS=error`.
> properly close pipes and sockets

- pyzo/codeeditor/extensions/autocompletion.py
When the cursor is at the bottom of a shell or editor widget, an autocompletion popup will occlude other widgets that are below. This is a bit annoying when having the "Interactive help" tool below the shell, as shown in the following picture.
Currently, the autocompletion popup will only switch from expanding downwards to expanding upwards when it would go deeper than the bottom border of the Pyzo main window.
With this PR, the autocompletion popup will expand upwards when it would go deeper than the shell resp. editor widget bottom border. The scene from above would then look like this:
> keep autocompletion popup within the shell/editor widget

- pyzo/codeeditor/extensions/autocompletion.py
- pyzo/core/baseTextCtrl.py
- pyzo/resources/defaultConfig.ssdf
This PR will remove two unused settings in defaultConfig.ssdf: "autoComplete_fillups" and "homeAndEndWorkOnDisplayedLine".
Both entries have never been used as far as the commit history goes back here on GitHub.
And for the third entry, that has also not been used, "autoComplete_caseSensitive", I have added code to implement that feature.
> Fix unused default settings

- pyzo/core/codeparser.py
The "Source structure" tool listed ToDo-Type entries "todo" and "2do" but not "fixme".
This PR adds the "fixme" detection to the core codeparser so that it behaves the same as the codeparser for syntax highlighting in the editor.
> fix parsing/detection of "FIXME" in comments

- pyzo/tools/pyzoFileBrowser/proxies.py
This change will increase the speed of searching text via the File Browser tool by a factor 5 to 10 -- tested on Linux when searching in the Pyzo code base.
This PR sets `QUEUE_DELAY` to 0.1 ms (instead of 10 ms). The `IDLE_DELAY` value remains at 10 ms, so there should be no negative impact on CPU load or battery energy usage while not searching.
> increase search speed in File Browser tool

- pyzo/_start.py
As reported via https://github.com/pyzo/pyzo/issues/946#issuecomment-1947920124, files cannot be opened anymore via file association on Mac computers.
```
fname = '/path/to/script/tobeopened.py'
sys.argv = ['/path/to/pyzo']
sys.argv[-1:] = [fname]  # <-- bug is here
res = commandline.handle_cmd_args()
args = sys.argv[1:]  # <-- args is then an empty list
```
This seems to be a bug introduced by #923.
In #923, two files were changed:
I fully know about the problem and its solution that lead to changes in file `pyzo/pyzokernel/start.py`.
But I have no idea, what the reason was to also modify file `pyzo/_start.py` in that PR.
> fix file opening via QFileOpenEvent on Macs

- pyzo/codeeditor/extensions/behaviour.py
- pyzo/codeeditor/parsers/python_parser.py
Actually, I only wanted to fix the following bug:
Syntax highlighting for a normal string literal that has a line-continuation backslash does not work, e.g.:
```python3
s = 'abc\
def'
```
While fixing this and testing, I encountered several bugs that are related (and were already present before this PR).
The first commit adds some missing bult-in identifiers for newer Python versions.
The second commit fixes some comments for the parser regular expressions that probably got mixed up when reformatting the code.
The third commit adds the line-continuation with backslash for normal strings, as described at the beginning.
When testing auto-completion with the line-continued string I saw that, when entering `[`
```python3
s = 'abc\
def  [   \
'
```
autocompletion added the `]` which should not …
> fix Python syntax parser and quotes/brackets autocompletion

- pyzo/core/editorTabs.py
- pyzo/core/main.py
During start of Pyzo, editor tabs are created that restore the recently opened files. Also the text cursor positions are moved to the position they had last time. But the problem is that this happens before the widgets are painted the first time and therefore the editor widget is too small and has to shift the horizontal scrollbar far to the right to keep the text cursor visible. When Pyzo is fully loaded, the editor widgets have the proper size, but the scrollbars remain shifted. This is a bit annoying because (depending on the restored text cursor column) you always have to first set the cursor to the very left to not miss anything on the left when browsing the code vertically.
To fix that, I just moved the call to `restoreEditorState` right after the first `paintNow()` call.
> fix initial horizontal scrollbar positions for editors

- pyzo/core/main.py
Sorry for the inconvenience. I just discovered that this did not work on the MS Windows version. Fixed that.
> fix for fix initial horizontal scrollbar positions for editors

- pyzo/core/baseTextCtrl.py
Function `parseLine_autocomplete` has confusing variable names:
```python3
def parseLine_autocomplete(tokens):
...
return needle, name
```
because everywhere else, the names are the other way round:
```python3
name, needle = parseLine_autocomplete(tokens)
```
This PR will fix the names and make the Pyzo source code easier to read.
> fix variable names in parseLine_autocomplete

- pyzo/core/baseTextCtrl.py
- pyzo/core/editorTabs.py
The current detection of already opened files solely relies on case sensitivity.
With the new implementation, symbolic links and network addresses (`r"\\localhost\c$\temp\abc.py" and r"C:\temp\abc.py"`) will also be recognized as the same file.
> fix detection of already opened files

- pyzo/codeeditor/extensions/appearance.py
Currently, the matching occurrence highlighter only accepts valid Python identifiers but not number literals.
```python3
needle = 0x13992B232623056
haystack = [
0x139928232622992,
0x139928232623056,
0x139928232622992,
0x139928232623056,
0x139928232622992,
0x13992B232623056,
0x139928232622992,
0x139928232623056,
0x139928232622992,
0x139928232623056,
]
```
I removed that restriction.
With the new implementation, the editor or shell will highlight selections that
* have no leading or trailing whitespace (but may contain whitespace)
* contain no line breaks (`"\u2029"` because of `QPlainTextEdit`)
* start and end with a word boundary (because of the `FindWholeWords` flag)
> make matching occurrences highlighter less restrictive

- pyzo/core/codeparser.py
The source structure tool displayed entries for TODO type entries (such as TODO, FIXME, etc.) always converted to lowercase.
I changed the code to keep the original case.
> preserve case for TODO-type entries in Source Structure tool

- pyzo/pyzokernel/magic.py
When entering a command in the shell that has a comment ending in a question mark, the command is misinterpreted as a magic command, e.g.:
```python3
b = a > 0  # is valid?
```
is converted to
```python3
print(b = a > 0  # is valid.__doc__)
```
I added a check to fix that.
> fix magician confused by comment ending with question mark

- pyzo/core/shell.py
This will allow to open also Python scripts with [UNC filepaths](https://en.wikipedia.org/wiki/Path_(computing)#UNC) in MS Windows when double clicking the filepath for example in a traceback in the shell.
> fix opening UNC paths in MS Windows via tracebacks

- pyzo/codeeditor/extensions/appearance.py
The `doc.FindWholeWords` flag in the `doc.find(...)` method for the matching occurrences highlighter does not treat the underscore as a word character. When, for example, selecting a variable `data`, then variable `another_data` would also be partially highlighted. This problem is similar to #276.
With this fix, an identifier or numeric literal will only be highlightes if it is the same as the selected one.
> fix matching occurrences highlighter word detection

- pyzo/core/editorTabs.py
- pyzo/core/main.py
- pyzo/core/menu.py
This will add a new menu entry "Reload from disk" to the "File" menu. This is especially useful when file change notification does not work properly on network shares.
> add "Reload from disk" to the File menu

- pyzo/codeeditor/extensions/appearance.py
How to reproduce the problem:
create a new file in the Pyzo editor
enter "1" in the first line
set a breakpoint at the first line
run the script
execution is stopped at the breakpoint in line 1 but the green marker is not shown (this problem occurs only for the first line)
This is an index-off-by-one bug. I fixed that.
> fix green debug position marker not shown for first line

- pyzo/codeeditor/extensions/behaviour.py
- pyzo/codeeditor/highlighter.py
- pyzo/codeeditor/parsers/__init__.py
- pyzo/codeeditor/parsers/c_parser.py
- pyzo/codeeditor/parsers/python_parser.py
- pyzo/codeeditor/parsers/s_expr_parser.py
- pyzo/core/shell.py
This will add proper syntax highlighting for the keywords "match" and "case" but only if they are used in such a way.
See the doc string of method `_promoteMatchCaseSoftKeywords(tokens)` for details and examples.
This will also close issue #841.
> add support for soft keywords "match" and "case"

- pyzo/qt/QtGui.py
This will fix a warning that was printed when hovering the mouse over the "Font" menu when using PySide6.
And I also added the line `del QtGui` to remove `pyzo.qt.QtGui.QtGui`.
> fix QFontDatabase deprecation warning for PySide6

- pyzo/pyzokernel/magic.py
When entering the command `cls = None` in the shell, pressing RETURN, and then entering `cls` and pressing RETURN, the magic command "clear screen" is executed instead of showing the value of the variable.
I found the bug and fixed it.
> fix misinterpretation of variables as magic commands

- pyzo/pyzokernel/guiintegration.py
`asyncio.get_event_loop()` is deprecated since Python 3.12. This caused an error in a Pyzo shell with an asyncio event loop when having set environment variable `PYTHONWARNINGS=error`. Fixed that.
> replace deprecated asyncio.get_event_loop()

- pyzo/pyzokernel/interpreter.py
logging.warn is an alias to logging.warning since Python 3.3 and will be removed in Python 3.13.
> Replace logging.warn usage with logging.warning

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Excluding PySide6 v6.7.0 because it is broken -- see issue #984.
> exclude broken PySide6 6.7.0 from CI and CD workflows

- .github/workflows/ci.yml
CI workflow runs with "macos-latest" image, Python 3.9 and PySide2 suddenly started to fail.
Two weeks ago, "macos-latest" was
https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240406.2
but now it is
https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240422.3
As far as I have read, PySide2 is not available for Apple's ARM CPU. Therefore I changed the workflow to use the older Intel-CPU macOS image for the PySide2 configuration.
> use macOS Intel image for CI with PySide2 instead of Apple Silicon

- pyzo/core/shell.py
**How to reproduce the problem**
start pyzo
close the shell
(optionally start a new shell)
set a breakpoint
--> error message "Uncaught Python exception: Cannot send from closed StateChannel" will appear in the Logger tool and in the status bar
**Root cause analysis and fix**
During the shell creation, a `breakPointsChanged` callback is registered. But this callback was never unregistered and kept being called when updating breakpoints, causing the error message.
I added a code line to unregister that callback when the shell is closed.
> disconnect breakpoint-changed callback when closing shell

- pyzo/pyzokernel/guiintegration.py
Alt solution to #989. It catches the interrupt exception and restarts the loop.
> Catch keyboardinterrupt in asyncio loop

- pyzo/yoton/clientserver.py
When running Pyzo from source with `PYTHONWARNINGS=error` in MS Windows, a "ResourceWarning: unclosed socket" appeared.
This PR will properly close the socket.
> properly close socket when aborting via an exception

- pyzo/pyzokernel/interpreter.py
When executing seleted lines of code in the editor with a syntax error, the relative line number was not converted to the absolute line number:
```
>>> (executing lines 4 to 8 of "asdf.py")
File "/tmp/aa/asdf.py+3", line 4
z = x / y /
^
SyntaxError: invalid syntax
```
After this fix, it works as expected:
```
>>> (executing lines 4 to 8 of "asdf.py")
File "/tmp/aa/asdf.py", line 7
z = x / y /
^
SyntaxError: invalid syntax
```
**Fixes**
There were two bugs:
1. The exception variable `value` cannot be directly unpacked in Python 3 -- this only worked in Python 2. Unpacking `value.args` instead works for all Python versions.
2. The tuple in `value.args[1]` got two extra values since Python v3.10 that contain `end_lineno` and `end_offset`. This was not accounted …
> fix relative line number correction in showsyntaxerror

- pyzo/core/shell.py
The foreground colour was not resetting in the shell when using the ANSI foreground reset code. Fixes #996
> Fix foreground colour not resetting in the shell when using the ANSI foreground reset code

- pyzo/pyzokernel/interpreter.py
When executing only selected lines, the line number is corrected for syntax errors. But this did not work for subclasses of `SyntaxError`, such as `IndentationError`.
For example, when running the middle cell of
```python3
pass
##
if True:
pass
##
```
The error message contained `File "<tmp 1>+2", line 3`.
After this fix, the corrected line number will be displayed in the error message:
`File "<tmp 1>", line 5`
> extend showsyntaxerror for SyntaxError subclasses

- pyzo/pyzokernel/debug.py
Using the "Interrupt" ("Shell -> Interrupt" or Ctrl+I) while the interpreter is in debug mode will keep the shell stuck in the debugging mode.
Steps to reproduce the problem:
1. start a new shell in Pyzo
2. cause an exception, e.g. via running `assert False`
3. enter post-mortem debugging (e.g. via Ctrl+P)
4. select "Shell -> Interrupt" or press Ctrl+I
5. try to stop debugging via "Shell -> Stop debugging" --> not possible anymore
This problem also occurs for regular breakpoints instead of post-mortem.
This PR will fix the problem.
> fix keyboard interrupt for active debugger

- .github/workflows/cd.yml
- .github/workflows/ci.yml
PySide6 v6.7.1 solved the problems that ocurred with v6.7.0 (see issue #984) -- we can remove the version restrictions introduced via PR #986.
> remove PySide6 restrictions in CI and CD workflows

- pyzo/pyzokernel/interpreter.py
I have removed a restriction for pausing executed code so that gui event loops can also be paused.
Code for testing:
```python3
import time
import os
if __pyzo__.guiName == 'PYSIDE6':
os.environ['PYZO_PROCESS_EVENTS_WHILE_DEBUGGING'] = '0'
from PySide6 import QtGui, QtCore, QtWidgets
cnt = 0
def callback_timer():
global cnt
print('event loop', cnt)
cnt += 1
if cnt > 10:
my_timer.stop()
print('finished')
my_timer = QtCore.QTimer()
my_timer.timeout.connect(callback_timer)
my_timer.start(500)
elif __pyzo__.guiName == 'ASYNCIO':
import asyncio
def bar():
for cnt in range(10):
print('event loop', cnt)
time.sleep(0.5)
print('finished')
loop = asyncio.get_running_loop()
loop.call_soon(bar)
print('press pause now to interrupt regular script')
for a in range(10):
print(chr(ord('a') + a)) …
```
> allow pausing of code in the event loop

- pyzo/core/editor.py
- pyzo/core/editorTabs.py
I have seen that the buttons of the dialogs "reloading of modified file" and "reload from disk" did not work anymore with PySide6 v6.7.1, and therefore I fixed that.
> fix reload dialogs for PySide6

- pyzo/core/editor.py
When pressing the right mouse button or the [menu key](https://en.wikipedia.org/wiki/Menu_key) in the editor, the editor's context menu will appear.
With this PR, I will fix the behavior to be similar to other popular editors, which is more intuitive in my opinion.
When invoking the context menu by a right mouse click and when there was no text selected, the text cursor will be moved to the mouse cursor's position. All subsequent actions in the context menu, such as paste, indent, comment, run selection, ... will therefore operate on the new text cursor position. Before this PR, these actions were performed on the text cursor position no matter at which position the mouse was clicked at (except for "help on this expression"), so one had to first left click on the line to comment and then …
> fix context menu behavior in editor

- pyzo/core/menu.py
This will add an entry in the editor tab context menu to close all the editor tabs to the right (resp. below in the editor list).
> add "Close all after this" entry to the tabs context menu

- pyzo/codeeditor/extensions/behaviour.py
- pyzo/core/baseTextCtrl.py
- pyzo/core/menu.py
The autoclose settings were not implemented in a clean way -- the `codeeditor` module had hardcoded access to the `pyzo` module to get the settings. I changed this to be more like other editor settings.
After this PR, there is no more dependency of the `codeeditor` module on `pyzo` (except qt.py).
> make codeeditor autoclose settings independent of pyzo

- pyzo/pyzokernel/debug.py
- pyzo/pyzokernel/interpreter.py
There was an issue when the debugger is activated inside a list comprehension (not mater if by breakpoint or pause).
The problem only occurs for 3.0 <= PythonVersion < 3.12 -- with Python 2.7 and 3.12 there would be no need for the workaround implemented in this PR.
The following example can be used to reproduce the problem and test the fix:
```python3
[breakpoint() for _ in range(1)]
x = 1
y = 2  # set a breakpoint in this line once stopped in the upper breakpoint()
```
And there was another issue, also when the debugger is activated inside a list comprehension: Continuing execution via stepping did not work. I also fixed that.
> fix breakpoints and stepping after interruption in list comprehension

- pyzo/pyzokernel/debug.py
With this fix, jumping in code that was executed as a cell or as a selection will also work correctly.
> fix jumping for code execution with line offset

- pyzo/core/menu.py
I see no reason why the menu entry for clearing all breakpoints was disabled during debug mode. Breakpoints can be removed one by one anyways, and breakpoints are updated always when executing new code or running a debug command.
It is more comfortable to have that action always enabled, for example to be able to continue execution in full speed mode (without tracing).
> allow "clear all breakpoints" action also in debug mode

- README.md
- pyzo/resources/tutorial.py
Closes #1021
I also updated the main website at https://pyzo.org
This does require people who want to ask a question to create a GH account. But for the target audience that seems fine.
> refer to GH discussions rather than google groups

- pyzo/core/codeparser.py
- pyzo/core/editor.py
- pyzo/core/menu.py
- pyzo/qt/__init__.py
- pyzo/qt/qtutils.py
- pyzo/tools/pyzoSourceStructure.py
Before this PR, the source structure tool did not update the cursor when just navigating around without editing the text. So I implemented this and some other features and optimizations:
- update of the selected item in the tree widget even when just navigating
- improved performance (e.g. by caching)
- output of the current (nested) class/method/function in the status bar
- added module pyzo.qt.qtutils with functions isOwnedByPython and isDeleted
- added results buffer to parser because there were sometimes timing problems
I recommend to have the status bar activated. Then the source structure tool will give you information about the current class, method and function. For example when setting the cursor in funtion `getBlocks` in pyzo/core/editor.py, then the following message will be …
> improve source structure tool

- pyzo/codeeditor/base.py
- pyzo/codeeditor/extensions/appearance.py
Before this PR, the breakpoints were displayed in the vertical bar (on the left of the editor) with a fixed pixel size. Zomming in to have larger font size did not change the circle size and had them aligned to the top of the line.
This PR changes the size of the red breakpoint circles (and similar indicators in the vertical breakpoint bar) proportional to the cursor height instead of having a fixed pixel height.
To implement this, I had to re-implement the handling of all vertical bar widths. This new implementation has the advantage that it removes the cyclic references between editor and breakpoint classes.
> implement scaled breakpoint visualization and remove cyclic references

- pyzo/core/baseTextCtrl.py
- pyzo/core/shell.py
- pyzo/pyzokernel/introspection.py
This PR adds some handy auto-completion features to Pyzo:
- better working call-tips for complex expressions like `abc = (myfunc(x + ((y + 2) + otherfunc(1, 2) - `
- key auto-completion (for dictionaries, lists and similar objects)
- auto-completion and calltips using a cached evaluated object, using the new shortcut Ctrl+Space
Examples for cached auto-completion:
Type `locals().` (with the **dot** at the end) and press Ctrl+Space. This will evaluate `locals()` and assign the result to `__pyzo__autocomp` in the local scope. Then auto-completion continues and displays the list widget with the **attributes**.
Type `locals()[` (with the **open bracket** at the end) and press Ctrl+Space. This will evaluate `locals()` and assign the result to `__pyzo__autocomp` in the local scope. Then …
> improve auto-completion and call-tips, and add key-completion

- pyzo/pyzokernel/introspection.py
The keys for non-dicts like `os.environ` or pandas dataframes can then be seen in the Workspace tool and used for key autocompletion.
> apply keys introspection to objects with keys method

- pyzo/codeeditor/extensions/behaviour.py
Currently, copying text in a text editor or shell will scroll to the end of the selected text.
For example, when opening a larger script (scrolled to the top) and pressing Ctrl+A and Ctrl+C, the editor/shell will be suddenly scrolled to the very bottom.
This is not normal behavior but a side effect of the overloaded `copy` method that implements the "smart copy" feature.
With this PR, the scroll position will be kept in such cases.
> keep vertical scroll bar position when copying text

- pyzo/core/editor.py
When saving in the editor (e.g. Ctrl+S) the Pyzo editor always scrolled to a position where the text cursor was visible. This was a side effect of `removeTrailingWS`.
I fixed that by saving and restoring the position of the vertical scrollbar.
> keep vertical scroll bar position when saving in the editor

- pyzo/codeeditor/extensions/calltip.py
Before this PR, moving the mouse cursor over the calltip closed the calltip.
The problem with that approach was that, before any calltip is active, a calltip would immediately be closed/hidden during typing when the mouse cursor was left in an unfavorable position before (inside the rectangle where the calltip would normally appear).
There are already many ways to close the calltip, for example finishing the parenthesis expression for the call, or pressing the ESC key, or clicking outside the text editor widget.
I had a look at other editors that show calltips and none of them closed the calltip on a mouse hover event (and also not on a mouse click event).
Therefore, this PR will remove the close on mouse hover mechanism for the calltips.
> do not hide calltip on mouse hover

- pyzo/core/baseTextCtrl.py
Changes the shortcut introduced in #1030, so it also works on MacOS.
----
The `ControlModifier` binds to the  `Command` key on MacOS (because in most use-cases that key is used where Windows users use `Control`, e.g. `Command+S` for saving a file).
The `Command+space` is a reserved key binding on MacOS that opens the spotlight. Therefore Pyzo cannot capture the `Command+space` shortcut.
In VSCode they had the same problem, and solved it by introducing `Command/Control + I` (capital i). However, we already use that for terminating the shell.
So this PR makes that it works with the actual `Control` key on MacOS (The `MetaModifier` means `Ctrl` on MacOS and Windows key on Windows/Linux).
> Autocomp mac

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- doc/.requirements
- freeze/pyzo_package.py
> Tweaks for MacOS builds

- pyzo/pyzokernel/introspection.py
Introspection of numpy array elements (scalars) failed for special types such as `np.dtype('U3')` (U3 ... three unicode characters).
This resulted in variables not showing up in the workspace tool.
For example:
```python3
import numpy as np
val = np.array(['abc'], dtype=np.dtype('U3'))[0]  # val did not show up in the workspace tool
```
This PR fixes the problem, and this also fixes issue #1051.
> fix introspection of non-numeric numpy elements

- pyzo/pyzokernel/introspection.py
I have encountered some numpy functions where calltips do not work.
This PR will strip the docstring before trying to get the signature from the first lines because some of them start with a newline and whitespace, e.g.:
`>>> np.where.__doc__[:34]`
`'\n    where(condition, [x, y], /)\n\n'`
With this PR, the following numpy functions will also have a calltip shown:
`bincount`, `can_cast`, `copyto`, `datetime_as_string`, `dot`, `empty_like`, `inner`, `lexsort`, `may_share_memory`, `min_scalar_type`, `packbits`, `putmask`, `ravel_multi_index`, `result_type`, `shares_memory`, `unpackbits`, `unravel_index`, `vdot`, `where`
> improve signature extraction for calltips

- pyzo/tools/pyzoInteractiveHelp.py
This adds a button for pausing automatic help from autocompletion.
Manual help will still work normally when paused (direct entry in the text field, or "Help on this expression" from the context menu, or "Show help" from the workspace tool).
I perceive the "pausing" action from the user as an indicator that the currently displayed doc string is important. Therefore the current entry gets also added to the history.
created in collaboration with user "heda" from https://forum.freecad.org
@almarklein: please also credit heda for this PR when writing the next release notes
> add pause button to "Interactive help" tool

- pyzo/pyzokernel/introspection.py
- pyzo/tools/pyzoExpressionViewer.py
- pyzo/tools/pyzoWorkspace.py
This PR adds a new tool "Expression viewer", updates the "Workspace" tool and adds the new method `evalMultiple`  in the introspector for evaluating multiple expressions used by the Expression viewer tool.
The "Expression viewer" is a kind of variable watch window that can be used for any expressions (not just variables). This also allows for custom formatting etc. by simply adding the python code for that in the expression. The results are normally updated automatically, the same as in the "Workspace" tool. For manual updates (e.g. when code is executed in the event loop), a manual refresh can be performed.
The GUI of the new tool consists of a small tool bar with buttons and a list resp. text widget.
The button with the pencil is a toggle button to enable the "edit mode".
In the "edit …
> add expression viewer tool

- pyzo/tools/pyzoWorkspace.py
This will allow to filter und update the variables while typing.
The "Starts with ..." option is activated by default, so typing some letters will show all variables starting with that letters.
> add "starts-with" and live-update to the workspace tool's search

- pyzo/core/menu.py
Old issue #470 seems to be fixed in Qt 5.15 LTS and Qt 6. Old workaround causes error "QAction::event: Ambiguous shortcut overload" now in latest Qt versions, at least when creating shortcuts for actions like "tool selection".
Fixes #1059.
> remove old workaround for shortcuts now causing issues

- pyzo/core/baseTextCtrl.py
- pyzo/tools/pyzoInteractiveHelp.py
The interactive help via the context menu only worked for selected text in the shell or editor, or for non-selected text under the mouse cursor if there was at least one dot in the simple expression (such as `foo.bar`). With this fix, it will also work for simple expressions without a dot (single variable).
And the initial text of the Interactive help tool stated that double clicking a name would trigger the interactive help, but this is not true (anymore). Therefore I fixed that as well.
> fix interactive help via context menu, and fix inital text

- pyzo/core/shellInfoDialog.py
With this PR, the startup-code textbox in the shell configuration dialog will display a placeholder text instead of setting empty configuration values to the after-gui marker. This is now more similar to the "environ" textbox which also uses a placeholder text.
> add placeholder text to startup-code textbox in shell configuration dialog

- pyzo/codeeditor/extensions/autocompletion.py
When "Auto close quotes" or "Auto close brackets" is activated and triggering key autocompletion for a dict like
`dd = {'abc': 0, "d'ef": 0, (1, 2): 3}`
by typing `dd['` there will be the characters `dd['']` and an autocompletion list with the single entry `'abc'`.
Accepting the completion suggestion by pressing TAB will then result in `dd['abc'']` with the closing quote twice: one because of the autocompletion entry and one that was there before from auto closing quotes.
The same happens for parens: After typing `dd[(` there will be the text `dd[()]` and the completion list with entry `(1, 2)`. Accepting the suggestion will result in `dd[(1, 2))]`.
This PR will fix that double closing quote (for single and double quotes) and that double closing parenthesis.
> avoid duplicated closing quote or paren on key autocompletion

- pyzo/codeeditor/style.py
This fixes a bug that caused different styles such as dark mode not to work.
> fix wrong enum for Qt6 in styles.py

- pyzo/codeeditor/extensions/autocompletion.py
- pyzo/codeeditor/extensions/calltip.py
As reported in #1068, Pyzo crashed when triggering the calltips text on Linux with Qt6, Wayland and gdm3.
I could reproduce the problem with such a setup, and I also found that Pyzo also crashed when triggering the autocompletion pop-up lists.
The first problem (calltips crash) was quite easy to fix -- after adding the parents assignment for the QLabel tooltip object, the crashes did not happen anymore.
The second problem was quite tricky to fix. I had to implement a specific workaround for the autocompletion pop-up list.
This workaround normally would also work on other operating systems, but to be on the safe side, I limited this workaround to be used only for Wayland environments.
> fix calltips and autocompletion crash with Qt6 on Wayland

- pyzo/codeeditor/extensions/autocompletion.py
- pyzo/core/baseTextCtrl.py
This PR will make it possible to properly use key autocompletion with, for example, negative numbers, numbers with multiple digits, numbers with a decimal point etc..
> fix autocompletion for numeric keys

- README.md
The Pyzo binaries do not properly work on newer Linux distribution versions.
Therefore I updated the installation instructions for Pyzo in the README.md file to recommend running Pyzo from source to Linux users.
> enhance installation instructions in README.md

- README.md
- freeze/pyzo_freeze.py
This PR adds some instructions for freezing Pyzo (e.g. building "Pyzo.exe" on MS Windows).
In pyzo_freeze.py I replaced "\_\_file\_\_" with an `inspect` expression so that the script can be normally executed inside Pyzo without the need of "Run file as script".
> improve freeze instructions

- pyzo/core/shell.py
- pyzo/qt/QtGui.py
This PR fixes two bugs that occurred when drag'n'dropping some selected text with the mouse into the shell widget.
One error was when using PyQt6 because of the missing fully qualified enum.
The other error was when using Qt5 because of the new `QDropEvent.position` method which only exists in Qt6.
> fix errors that occurred when dropping text in the shell

- pyzo/core/editor.py
- pyzo/core/editorTabs.py
- pyzo/core/main.py
- pyzo/core/menu.py
This PR adds a menu entry to create a backup of the current editor's contents, without modifying the editor's state.
And the file-save-as dialog, which is also used for saving the copy, now suggests not only the directory but also the filename if the current editor already had one before.
This feature was suggested by a user from the FreeCAD forum.
As far as I have seen, programs such as Notepad++, Gimp and LibreOffice also have such a feature.
I will wait around one week before merging this, so that there is time for review and suggestions.
> add "Save a copy as..." menu entry for creating file backups

- .github/workflows/ci.yml
PySide6 6.8.0 is broken, see issue #1088.
I will exclude it from the CI workflow for now, but keep it in the CD workflow.
> exclude broken PySide6 6.8.0 from CI workflow

- freeze/boot.py
For freezing Pyzo, file "boot.py" needs a fix to work with the new Qt wrapper, introduced via #1091.
The command `importlib.import_module("pyzo.qt.QtCore")` does not work anymore.
But as far as I have seen, it is not necessary, because the Qt modules will be imported later anyways.
@almarklein
Was there a special reason to do the Qt imports in boot.py (except the pre_qt_import)?
If there was an exception during importing the Qt libraries, the `BootAction("Running Pyzo")` would show the error message box anyways.
In case the import is necessary in boot.py, there are two alternatives:
```python3
from pyzo.qt import QtCore, QtGui, QtWidgets
```
or
```python3
_pyzo_qt_ = importlib.import_module("pyzo.qt")
QtCore = _pyzo_qt_.QtCore
QtGui = _pyzo_qt_.QtGui
QtWidgets = _pyzo_qt_.QtWidgets
```
> fix boot.py for new qt wrapper

- freeze/pyzo_freeze.py
- pyzo/qt/__init__.py
Since #1045 we don't need `QtHelp` anymore. This makes it a bit easier to run Pyzo from source when using the Linux distribution's package manager instead of pip. And this also saves a bit of memory for all binary releases.
> remove unused QtHelp dependency

- .github/workflows/ci.yml
The CI workflow gave the following error after I submitted the previous PR:
>The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see https://github.com/actions/runner-images/issues/10721
Therefore I updated `macos-12` to `macos-13`.
The CD workflow already had `macos-13`.
According to [the Qt page](https://doc.qt.io/qt-5/supported-platforms.html), Qt5 is supported for all CPU architectures.
> update macOS version in CI workflow to macos-13

- pyzo/codeeditor/extensions/calltip.py
I observed that, when the text of a visible calltip label is changed, the size of the whole calltip rectangle is not updated. This happens on all supported Qt wrappers.
Example:
In the last line of the following code, upon entering the first open parenthesis, the calltip of `myfunc1`, which is `myfunc1(param1=None, param2=None)`, is shown. As soon as the second open parenthesis is entered, the tooltip text is updated to
`myfunc2(p3, p4)                  `.
```python3
def myfunc1(param1=None, param2=None):
pass
def myfunc2(p3, p4):
pass
myfunc1(324, myfunc2(
```
This PR fixes the problem.
> fix wrong size of calltip label size after updating calltip text

- pyzo/pyzokernel/interpreter.py
This fixes issue #1101:
When using an IPython shell and having a breakpoint set, executing the first command in the shell, for example `pass`, the `AttributeError: 'Debugger' object has no attribute 'quitting'` was raised.
> fix debugger for ipython shells

- pyzo/pyzokernel/interpreter.py
As already reported in #645, logging does not work with a custom logging configuration:
```python3
import logging
logging.basicConfig(level=logging.DEBUG)
logging.debug('test debug')  # --> not shown
logging.info('test info')  # --> not shown
logging.warning('test warning')
logging.error('test error')
logging.critical('test critical')
logging.basicConfig(level=logging.DEBUG, force=True)
logging.info('test info after force')  # --> not shown
```
That problem was only mitigated a bit via https://github.com/pyzo/pyzo/pull/675/commits/8fc48a8568949f6afb148b9cd472d950f8d07df0 by displaying a warning message to inform the user about the ignored logging configuration.
The usage of the `logging` module in the interpreter was introduced via …
> remove limitations for usage of Python's logging module

- pyzo/pyzokernel/interpreter.py
I found that `ExceptionGroup` exceptions are not formatted correctly: all the sub-exceptions are swallowed. This is a problem e.g. when working with trio. The reason is that we examine and tweak the traceback to resolve line number offsets.
This PR just lets Pythons traceback formatter do the work, and then fix the linenr offset by examining the resulting string lines.
> More rubust tracebacks

- pyzo/pyzokernel/interpreter.py
Follow-up on #1103
The ability for setting up PM debugging when a ``logger.error()`` is quite generally useful IMO. Basically any case where there is some sort of event-loop that catches and logs exceptions instead of letting them fall through. In any case, I make use of it a lot :)
I took some time to look into what the least invasive approach could be, and come to the conclusion that adding a handler will always hurt one use-case or another. So I applied a somewhat dirtier monkey-patch, but that otherwise leaves the logging system alone.
> Enable pm for logging again

- pyzo/tools/pyzoFileBrowser/proxies.py
This fixes a minor bug in an error message.
Normally, that error message cannot occur because there is already [another check with its own error message at a higher level](https://github.com/pyzo/pyzo/blob/3201ab5db5dd0126499c0f42ff494952ad70ca6a/pyzo/tools/pyzoFileBrowser/tree.py#L993-L1002).
Found via `ruff check`, by the way.
> fix error message in filebrowser tool

- pyzo/pyzokernel/interpreter.py
PR #1104 broke exception formatting for older Python versions.
When starting a shell with Python < v3.10 and evaluating a variable that does not exist, instead of the `NameError` another error is displayed in the shell:
```
>>> a
An error occured, but then another one when trying to write the traceback: format_exception() takes at least 3 arguments (1 given)
```
And there was also another small bug: Line `for i in range(max(len(lines), 5)):` would iterate over at least 5 lines even if there were less, and then cause an IndexError. Probably that should have been a `min` instead of the `max`.
The third problem with PR #1104 was that it broke line number correction for temporary files:
The tracebacks then had
`File "<tmp 3>+4", line 6, in <module>`
instead of
`File "<tmp 3>", line 10, in …
> fix traceback for Python < v3.10 and for temporary files

- pyzo/tools/pyzoSourceStructure.py
This fixes #1110.
Previously, the white background color was also applied to the scrollbar of the source structure tool, which made it look different than all other scrollbars.
> fix style of scrollbar in source structure tool

- pyzo/core/shell.py
Before this PR, the `poll` timer callback method in class `PythonShell` was regularly called even after closing the shell.
> stop polling-timer when closing the shell

- pyzo/core/commandline.py
- pyzo/core/kernelbroker.py
- pyzo/pyzokernel/interpreter.py
- pyzo/resources/external_shell_examples/start_external_shell.py
This PR makes it possible to use externally started Python shells inside Pyzo.
With externally started shells, the Python interpreter of the shell is not started by Pyzo but outside Pyzo by a different application.
In the external shell, some custom start code for the Pyzo kernel has to be executed to create a shell in Pyzo. The Pyzo shell can be closed and re-opened again inside the same Python session. There is no need to add or modify any shell configuration in the "Shell configurations" dialog, since all the relevant information is part of the custom start code.
There are no changes in Pyzo's user interface.
Why could this be useful?
I have a use case where a Python interpreter is started from a third party application that lacks Pyzo's features such as post-mortem debugging and cell …
> add support for externally started shells

- pyzo/core/menu.py
The "Advanced Settings" dialog will automatically set the focus in the search textbox when opened.
This means that the user can immediately start typing the needle text after opening the dialog.
> set focus to search field when opening Advanced Settings dialog

- .github/workflows/ci.yml
The current CI workflow for Ubuntu 24.04.1 aborts with an error:
E: Unable to locate package libegl1-mesa
> fix ci workflow for Ubuntu 24.04

- pyzo/tools/pyzoFileBrowser/tree.py
I have experienced reproducible crashes of Pyzo, where the application is suddenly closed, on both Linux and MS Windows with the current binary version of Pyzo.
The crash happens when searching in the "File Browser" tool with an invalid regular expression as the needle, e.g. `a(`.
With this fix, the problem is detected early and an error message is displayed in the tree widget, e.g.:
```
Error in regular expression:
missing ), unterminated subpattern at position 1
```
> prevent crash on invalid regexp in filebrowser tool

- pyzo/pyzokernel/guiintegration.py
- pyzo/pyzokernel/introspection.py
- pyzo/pyzokernel/pipper.py
- pyzo/tools/pyzoInteractiveHelp.py
- pyzo/yoton/channels/channels_reqrep.py
- pyzo/yoton/tests/test_speed.py
Recent commits made Python 2.7 kernels crash in Pyzo.
#1121 removed the `"# -*- coding: utf-8 -*-"` headers from files executed by the kernel.
#1123 used the Python 2.7 keyword `exec` as an attribute, resulting in a SyntaxError
All files inside the folder `pyzo/pyzokernel` are executed only by the kernel (Python 2.7).
All files inside the folder `pyzo/yoton` are executed by both the Pyzo IDE (Python >= v3.6) and the kernel (Python 2.7).
All remaining Python files are executed only by the Pyzo IDE (Python >= v3.6).
I changed all Python scripts that are executed by the kernel so that they are (7 bit) ASCII files.
And I fixed the `exec` attribute and added an override for `ruff` to not touch that anymore.
> restore compatibility with Python 2.7 shells

- pyzo/qt/__init__.py
PR #1123 modified the Qt wrapper.
I changed it so that the namespace pollution is lower again.
And I also got rid of `ruff: noqa: F401` by writing `from . import qtutils as qtutils` instead of `from . import qtutils`.
> cleanup qt wrapper

- pyproject.toml
- pyzo/core/shell.py
- pyzo/resources/code_examples/pyzo_terminal_emulation.py
Before this PR, the terminal emulation in Pyzo had some flaws when text fragments were not processed in one go.
For example, there were sporadic problems with color format escape sequenes not working or sudden newlines instead of carriage returns. Line shortening for lines > 1024 chars sometimes printed longer lines on the text fragment boundaries.
I completely reworked the terminal emulation.
The best way to get a feeling for the new features is to execute the included example code script cell by cell:
https://github.com/pyzo/pyzo/blob/main/pyzo/resources/code_examples/pyzo_terminal_emulation.py
This also solves issue #744 from the year 2021.
> improve terminal emulation in Pyzo's shell widget

- pyzo/core/shell.py
- pyzo/pyzokernel/interpreter.py
Now, soft keyword such as `match` and `case` are also part of the autocompletion list.
> add soft keywords to autocompletion list

- pyzo/core/commandline.py
This PR adds support to open scripts in Pyzo by passing a relative filepath as the command line argument.
Before this PR, the command `pyzo ./abc.py` passed the relative path `./abc.py` to the Pyzo command server. The command server then resolved the relative path using the server's current path but not the client's current path.
With this PR, Pyzo resolves the relative path to an absolute path in the client code and then passes the absolute path to the server.
A relative path has to start with a dot, and the `open` command must not be used.
`pyzo ./abc.py` will work as intended now, but `pyzo open ./abc.py` would use the server's working directory.
@almarklein: Can you please test this on macOS because I also changed the `psn_` stuff?
This solves issue #752.
> support relative filepaths in Pyzo's command line arguments to open files

- pyzo/codeeditor/extensions/behaviour.py
- pyzo/core/baseTextCtrl.py
- pyzo/core/editorTabs.py
- pyzo/core/menu.py
- pyzo/resources/defaultConfig.ssdf
Before this PR, editor tab switching was a bit strange in Pyzo (at least on Linux and MS Windows):
`Ctrl+Tab` would only toggle between the currently and the previously selected editor tab.
`Ctrl+Shift+Tab` would switch to the tab that is on the left of the current tab.
The old implementation of the tab switching history was limited to only 10 entries and could contain invalid values (`None`). Now there is no such history length limit anymore, and the history is now always a subset of all open editor tabs.
I removed the "View -> Select previous file" menu entry with its shortcut and the default configuration value.
There were some bugs in `keyPressEvent` methods that needlessly ate `Ctrl+Tab` keypress events. These are now fixed.
With this new editor tab switching feature, a dialog with a …
> implement proper editor tab switching with history

- pyzo/core/baseTextCtrl.py
- pyzo/core/editorTabs.py
- pyzo/core/main.py
@almarklein:
Consider this PR a whiteboard for fixing tabswitching.
I added some commits that show what has to be fixed.
The first commit [use workaround only for macos](https://github.com/pyzo/pyzo/commit/aa14d4f97e7c113b8f5ef4d769482d9181f656f6) is more or less a placeholder for a proper fix.
I think, the problem can be quickly found by deactivating all the `keyPressEvent` methods in the folder "pyzo/codeeditor/extensions" -- just comment out the lines and add a `pass` instead. At least, this is how I did it when I fixed that for Linux.
Commit [fix return statement for PyQt6](https://github.com/pyzo/pyzo/commit/5d978f1b1318c14516b317e3992f3303f6199e7a) is necessary because PyQt6 throws an exception if there is a value returned from the keyPressEvent.
There was also a `print` call from …
> fix tabswitching

- pyzo/qt/qtutils.py
This is just a small fix to a function that is currently not used by Pyzo.
> update shiboken attributes in qt wrapper

- pyzo/codeeditor/extensions/autocompletion.py
- pyzo/codeeditor/extensions/calltip.py
- pyzo/core/baseTextCtrl.py
- pyzo/tools/pyzoInteractiveHelp.py
Before this PR, the "Interactive help" tool dynamically displayed the help text for the currently selected item in the autocompletion list.
I reworked this so that also calltips will tell the interactive help tool to display the help text for the current function/method.
If both, the autocompletion list and the calltip are shown at the same time, autocompletion takes precedence for the displayed help text.
> show interactive help for active calltip

- pyzo/tools/pyzoFileBrowser/__init__.py
- pyzo/tools/pyzoFileBrowser/browser.py
- pyzo/tools/pyzoFileBrowser/tasks.py
This PR fixes some issues of the filebrowser tool:
When doing a case insensitive search and using a RegExp pattern as the needle, the needle was converted into lowercase, and this turned `\B` into `\b` which has a different meaning in regular expressions. --> fixed
When invoking "Edit -> Find via File Browser" (or Ctrl+Shift+F), the selected text in the editor is searched via the filebrowser tool. But the problem was that this would not always work when option "RegExp" was activated. Now, the needle from the editor will automatically be escaped into a regular expression in the filebrowser search text box.
And this PR adds a new feature:
Now there is a new "Whole words" search option in the filebrowser tool with same behavior as in the code editor's search.
> fix filebrowser regexp search and add "whole words" option

- pyzo/tools/pyzoFileBrowser/browser.py
- pyzo/tools/pyzoFileBrowser/proxies.py
- pyzo/tools/pyzoFileBrowser/tasks.py
- pyzo/tools/pyzoFileBrowser/tree.py
This PR fixes some minor issues I encountered in the filebrowser tool:
The peek task which extracts top level class and function definitions interpreted an identifier `default` as function `def ault`.
A method name was wrong, but that code line was never executed anyways.
And I also fixed some typos in comments and docstrings.
> fix minor issues in filebrowser tool

- pyzo/core/main.py
This fixes a bug that I introduced via #1139.
During startup of Pyzo, when the splash screen was shown and the editors were not initialized yet, a key press raised an exception that aborted the application start.
> prevent crash on key press during Pyzo startup

- pyzo/__init__.py
- pyzo/core/shellInfoDialog.py
- pyzo/pyzokernel/guiintegration.py
- pyzo/pyzokernel/interpreter.py
This will remove the support of event loops for PySide and PyQt4 in Pyzo kernels.
The reason is to make the Pyzo code easier to maintain and extend.
> remove support for Qt4 GUI event loops

- pyzo/tools/pyzoLogger.py
This PR makes it possible to insert and execute whole code blocks in Pyzo's Logger tool.
For example, the following code block can now be copied to the clipboard and then pasted and executed in the Logger tool:
```python3
def my_func(a, b):
print('my_func', a, b)
my_func(1, 2)
```
> allow execution of multiple lines in the Logger tool

- pyzo/core/menu.py
Up to now, the "Find via File Browser" action (e.g. triggered via Ctrl+Shift+F) copied the selected text in the editor to the search box of the file browser tool, no matter if the editor had the focus or not.
I modified the behavior so that the selected text in the editor will only be used as the needle if the editor widget has the keyboard focus. If the focus is in the shell instead, the selected text in the shell will be used as the needle. The same logic now goes for selected text in the "Logger" tool and the "Interactive help" tool.
> enhance "Find via File Browser" to use selection from widget with focus

- pyzo/core/editor.py
- pyzo/core/editorTabs.py
- pyzo/core/menu.py
- pyzo/core/statusbar.py
> use file encoding information according to PEP 263

- pyzo/pyzokernel/interpreter.py
This improves the support of encodings in files when they are run **as a script** (via `PyzoInterpreter.runfile(...)` in the kernel).
For Python 2.7 this means a support of an optional BOM_UTF8. The parsing of the magic PEP 263 comment is still only partially implemented -- for example no support for the encoding information in the second line.
For Python 3 this means the best possible recognition of the encoding via `tokenize.detect_encoding`. This also correctly detects a BOM_UTF8.
Not to be confused with "Execute file/cell/..." in the "Run" menu which all use the source code decoded by the editor.
> support encodings and BOM in files when run as script

- pyzo/core/editor.py
- pyzo/core/editorTabs.py
- pyzo/resources/defaultConfig.ssdf
Before this PR there was the danger of data loss after reloading:
User adds changes to a file and saves it (and keeps the file open in the Pyzo editor).
An external program rewrites the file.
The user switches focus in Pyzo and gets the "File was changed" dialog.
User presses "Keep this version".
User closes Pyzo. Changes are lost because Pyzo does not even ask to save the version in the editor.
With this PR, when pressing "Keep this version" the document in the editor is marked as modified.
Pyzo does a file modification check as well when the user saves the file (e.g. via Ctrl+S).
Before this PR, the check displayed a message box with choices "Keep this version" and "Reload". In my opinion, "Reload" is a bit out of place when saving a file.
With this PR, the check while saving gets its …
> improve editor file reloading and add automatic reloading

- pyzo/core/shell.py
```python3
class MyClass:
def my_method(self):
pass
```
When the code above is entered in the editor, without having a `MyClass` object in the shell, autocompletion for object `MyClass` is done via parsing the code ("fictive" class members, etc.).
When typing `MyClass.m` in the editor, autocompletion immediately suggests `my_method`, so this works fine.
But when only typing `MyClass.` in the editor, there is no autocompletion list.
The cause of the problem was that with `MyClass.` Pyzo expected `MyClass` to be a Python package that was not yet imported and tried to do an auto-import, but there is no line `import MyClass` in the editor. Then Pyzo proceeded to abort autocompletion even though there were detected fictive class members in the auto completion list.
I fixed that, so that …
> fix autocompletion for parsed class members (without introspection)

- pyzo/core/shell.py
Autocompletion with auto-import is supposed to automatically import a module and then show the autocompletion list.
For example, when starting a new shell and creating a new editor with the contents
```python3
import sys
...
```
and then typing `sys.`, the command `import sys  # auto-import` is automatically executed in the shell after typing the dot, but in reality, no autocompletion is shown.
As far as I have seen, this is an old bug which was introduced in Pyzo 3.0 (around 13 years ago).
Instead of re-trying the `dir` introspection method after the import, the call signature was requested, which makes no sense.
When using an enum class, there was an autocompletion list, but the list entries were just the unique characters of the call signature string:
```python3
import enum
class …
```
> fix autocompletion with auto-import

- pyzo/core/editor.py
Autocompletion for enum classes does not list the enum members (via introspection), for example:
```python3
import enum
class MyEnum(enum.Enum):
my_value1 = 1
my_value2 = 2
MyEnum
```
This is because method `processAutoComp` changes the name of the object to be introspected from `MyEnum` to `enum.Enum`.
With the changes in this PR, autocompletion will use the actual class as the object to be inspected, e.g. `MyEnum` for the example above. This will then show the enum values in the autocompletion list.
@almarklein:
This change of `nameForShell` was done when a base class was not found in the "fictive" namespace from the editor's code parser, and this was already since the first Pyzo version 2.1 that I encountered on GitHub. Is there any case where this change of `nameForShell` is …
> improve autocompletion for derived classes via introspection (e.g. enum.Enum)

- pyzo/core/shell.py
- pyzo/resources/code_examples/pyzo_terminal_emulation.py
Text formatting via terminal emulation escape sequences did not work properly for escape code 39 ("default foreground color").
The problem can be reproduced by executing
`print('normal  \x1b[39m should also be normal  \x1b[0m normal')`
The bug causes the text "should also be normal" to be printed in black.
This PR fixes the problem.
> fix resetting color in terminal emulation

- pyzo/codeeditor/extensions/autocompletion.py
Autocompletion will now always be canceled when clicking in the QPlainTextEdit widget. This is a more general approach than #1180.
> always close autocompletion pop-up when clicking in the editor resp. shell

- pyzo/tools/pyzoSourceStructure.py
- Change font of source structure tool to match codeeditor
- force update of source structure tool when font of code editor changes
- update cell display text to be of length 120 at least to align the underlining.
This change was motivated by the fact that the underlining isn't justified in the source structure tool for comment cells, which is quite visible in files with a lot of cell comments. This stems from two sources:
1. A fixed pad of 120 whitespaces after the cell name
2. The use of a non-monospace font (sans serif, I think).
Therefore, I propose a change that forces the font of the source structure to match the font of the code editor (which is always monospace), and pad the name of the cell comment to 120 rather than add 120 whitespaces.
> SourceSctructure font change and comment cell display

- pyzo/codeeditor/extensions/behaviour.py
Hi,
This is a very small PR to make double-quoting consistent for upper-case and lower-case string litteral.
type any valid lower-case string litteral identifier such as `f`, then press a quote as if to open a string `"`. This quote should automatically be doubled:
now do the same for an upper case string litteral (`F` here):
Note that this behavior is the same even if the string identifer is only partly upper-case:
Now a double quote is added as long as the prefix is valid:
> Fix auto-closing quotes for upper case string literal prefixes

- pyzo/core/menu.py
The first commit is some general clean-up of the code for the "Edit shortcut mapping" dialog. The sizes and positions of widgets (labels, text input, buttons) were hard-coded in pixels. I changed this to a dynamic layout.
The second commit fixes an issue with recording shortcuts in Linux:
Pyzo already has a default keyboard shortcut that uses Ctrl and Shift combined with a number: Ctrl+Shift+3 for toggling a comment. But it is not possible to record such a shortcut in Linux with Pyzo's "Edit shortcut mapping" dialog because the `3` is converted by the operating system into the shifted `#` when using a [US keyboard layout](https://en.wikipedia.org/wiki/File:KB_United_States.svg). MS Windows does not have this problem because the native key can be accessed via Qt which reveals the `3` for …
> support more key shortcuts with Shift modifier in Linux

- pyzo/core/menu.py
This adds entry "Open directory outside Pyzo" to the context menu of editor tabs, which is also the context menu in the "Editor list" tool. The directory, which contains the file, will then be opened in the operating system's file browser. In MS Windows, the file will even be selected.
> add "Open directory outside Pyzo" to editor tab context menu

- pyzo/core/statusbar.py
The label on the very right of the status bar will now have dynamic width. This prevents larger numbers of line number, column number and selection length to be cut off.
> set cursor info text in status bar to dynamic width

- pyproject.toml
Ruff 0.13.0 introduced a new rule RUF059 that made the linter complain about unused unpacked variables, for example: `protocol, hostname, port = split_address(address)`
RUF059 would complain if any of the three variables is not used afterwards
I added this rule to the ignore list because the variable names give useful information about what the function is returning besides the used variables.
> ignore newly introduced rule RUF059 in ruff linter

- pyzo/resources/code_examples/snippets_example.py
- pyzo/tools/pyzoSnippets.py
When starting Pyzo with the Snippets tool enabled there was a warning in the console:
`QLayout: Attempting to add QLayout "" to PyzoSnippets "", which already has a layout`
I fixed that and also added two more code snippets to the examples.
> fix Qt warning in Snippets tool and add more snippets

- pyzo/core/editorTabs.py
* create a new editor tab \<tmp x\>
* enter any valid Python command, e.g. `a = 1`
* set a breakpoint in that line
* save the file, e.g. as "/tmp/aa.py"
* run the file via Run -> Execute file
--> The code is executed but breakpoint is not triggered because it is still registered as file "\<tmp x\>" instead of "/tmp/aa.py".
I added some code to update the breakpoints when the file in the editor is saved as a new/different file.
And I removed an unused assignment.
> fix update of breakpoints after changing filepath in editor

- pyzo/pyzokernel/pipper.py
When using the magic commands `pip install some_package_name` or `pip download some_package_name`, the displayed progress bar was not updated anymore with newer pip versions -- the progress bar was only printed when it already had 100 %, because pip did not send more updates to stdout.
I reworked the code so that for new pip versions >= v24.1 (released 2024-06-20) the progress bar updates work again, and I kept the old approach as a fallback solution for older pip versions.
See the large docstring at the beginning of pyzo/pyzokernel/pipper.py for more details.
> rework pip magic progress bar updates for newer pip versions
